<div id="vaimo_prevnextlocal_detail" class="vaimo_prevnextlocal_main">
    <div class="vaimo_prevnextlocal_under">
        <div class="vaimo_prevnextlocal_side">
            <div class="vaimo_prevnextlocal_data">
                <img id="vaimo_prevnextlocal_detail_image" src="media/consumersales/5.png">
            </div>
        </div>
        <div class="vaimo_prevnextlocal_side">
            <div class="vaimo_prevnextlocal_under">
                <div class="vaimo_prevnextlocal_side"><div id="vaimo_prevnextlocal_detail_name"></div></div>
            </div>
            <div class="vaimo_prevnextlocal_under">
                <div class="vaimo_prevnextlocal_side"><div id="vaimo_prevnextlocal_detail_short_description"></div></div>
            </div>
            <div class="vaimo_prevnextlocal_under">
                <div class="vaimo_prevnextlocal_side">SKU:</div>
                <div class="vaimo_prevnextlocal_side"><div id="vaimo_prevnextlocal_detail_sku"></div></div>
            </div>
        </div>
        <div id="vaimo_prevnextlocal_list_end" class="vaimo_prevnextlocal_end"></div>
    </div>
</div>
<?php echo $this->getEventScript(); ?>