<?php

/**
 * Selected product widget small-format template extensions.
 * @category  Template
 * @package   carbon/hylete
 * @author    Rick Buczynski <rick@mediotype.com>
 * @copyright 2018 Mediotype
 */

?>
<?php /* @var $this Mediotype_HyletePrice_Block_Selectedproducts_Single */ ?>
<?php /* @var $this Mediotype_HyletePrice_Block_Selectedproducts_Widget */ ?>
<?php /* @var $_productCollection Mage_Catalog_Model_Resource_Product_Collection */ ?>
<?php $_productCollection   = Mage::helper('hylete')->getSelectedProductsCollection($this); ?>
<?php $_collectionSize      = $_productCollection->count(); ?>
<?php $_imageAttribute      = $this->getImageAttribute() ?: 'small_image'; ?>
<?php $_listTitle           = $this->getCollectionTitle(); ?>
<?php $_listDirection       = $this->getListDirection(); ?>
<?php $_columnCount         = $this->getNumGet(); ?>
<?php $_rowClasses          = $this->getRowClasses() ?: 'row'; ?>
<?php $_itemClasses         = $this->getItemClasses() ?: 'col-xs-12 col-sm-12 col-md-12 col-lg-12'; ?>

<?php if ($_listDirection == 'horizontal') : ?>
<?php $_itemClasses = 'col-xs-12 col-sm-4 col-md-4 col-lg-4'; ?>
<?php endif; ?>

<?php if (!$this->getIsCategoryListing() && !$this->getItemClasses()) : ?>
<?php $_itemClasses = 'col-xs-12 col-sm-3 col-md-3 col-lg-3'; ?>
<?php endif; ?>

<div class="selected-products category-products widget-size-small">

    <?php if (!$_collectionSize) : ?>
    <div class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </div>
    <?php else : ?>

    <?php if ($_listTitle) : ?>
    <div class="head">
        <h4><?php echo $_listTitle; ?></h4>
    </div>
    <?php endif; ?>

    <?php if ($this->getIsCategoryListing()) : ?>
    <div class="products-grid <?php echo $_rowClasses; ?>">
    <?php else : ?>
    <ol class="products-grid <?php echo $_rowClasses; ?>">
    <?php endif; ?>

        <?php foreach ($_productCollection as $_product) : ?>
        <?php $_status      = $_product->isSaleable() ? '' : ($_product->getComingSoon() ? 'coming-soon' : 'out-of-stock'); ?>
        <?php $_badgeLabel  = $_product->getBadgeLabel() ? $_product->getAttributeText('badge_label') : ''; ?>
        <?php $_tagName     = $this->getIsCategoryListing() ? 'div' : 'li'; ?>
        <<?php echo $_tagName; ?> class="item <?php echo $_itemClasses; ?> <?php echo $_status; ?>">

            <div class="badges">
                <?php if ($_badgeLabel) : ?>
                <div class="badge"><?php echo $this->escapeHtml($_badgeLabel); ?></div>
                <?php endif; ?>
            </div>

            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, $_imageAttribute)) ?>">
                <picture>
                    <source srcset="<?php echo $this->helper('catalog/image')->init($_product, $_imageAttribute)->resize(220); ?>" media="(max-width: 768px)">
                    <img srcset="<?php echo $this->helper('catalog/image')->init($_product, $_imageAttribute)->resize(500); ?>"
                         alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, $_imageAttribute)) ?>">
                </picture>

                <?php if (!$this->hasShowPriceAndName() || $this->getShowPriceAndName()) : // ಠ_ಠ ?>
                <h5><?php echo $this->htmlEscape($_product->getName()); ?></h5>
                <p class="color"><?php echo $_product->getAttributeText('color'); ?></p>
                
                <?php if ($this->getChild('msrp_price')) : ?>
                <?php echo $this->getChild('msrp_price')->addClass(($this->getIsCategoryListing() ? 'retail-value--category' : ''))->setProduct($_product)->toHtml(); ?>
                <?php endif; ?>

                <?php if ($_product->isSaleable()) : ?>
                <?php echo $this->getPriceHtml($_product, true); ?>
                <?php else : ?>
                <p class="status-message">
                    <?php echo ($_product->getComingSoon()) ? $this->__('coming soon') : $this->__('sold out'); ?>
                </p>
                <?php endif; ?>
                <?php endif; ?>

                <?php if ($this->getChild('multipack_offer')) : ?>
                <?php echo $this->getChild('multipack_offer')->setProduct($_product)->toHtml(); ?>
                <?php endif; ?>

                <?php if ($this->getShowBuyButton()) : ?>
                <?php if ($_product->getTypeId() == 'configurable' || !$_product->isSaleable()) : ?>
                <button type="button" title="<?php echo $this->__('More info'); ?>" class="button btn-cart hidden-phone" onclick="setLocation('<?php $_product->getProductUrl(); ?>');">
                    <span>
                        <span><?php echo $this->__('More info'); ?></span>
                    </span>
                </button>
                <?php else : ?>
                <button type="button" title="<?php echo $this->__('Add to Cart'); ?>" class="button btn-cart hidden-phone" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product); ?>')">
                    <span>
                        <span><?php echo $this->__('Add to Cart'); ?></span>
                    </span>
                </button>
                <?php endif; ?>
                <?php endif; ?>

            </a>

        </<?php echo $_tagName; ?>>
        <?php endforeach; ?>

    <?php if ($this->getIsCategoryListing()) : ?>
    </div>
    <?php else : ?>
    </ol>
    <?php endif; ?>
    <?php endif; ?>

</div>
