<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SubscribePro
 * @package   SubscribePro_Autoship
 * @author    Subscribe Pro Support <support@subscribepro.com>
 * @copyright 2009-2020 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<div class="page-title">
    <h1><?php echo $this->__("My Product Subscriptions") ?></h1>
</div>

<div id="mysubscriptions">
    <div class="subscription-blocks">
        <?php foreach ($this->getAllSubscriptions() as $subscription): ?>
            <div class="subscription-block">
                <?php echo $this->getLayout()->createBlock('autoship/mysubscriptions_subscription')
                    ->setTemplate('autoship/mysubscriptions/subscription.phtml')
                    ->setSubscriptionData($this->getSubscriptionData($subscription))
                    ->toHtml() ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<span class="please-wait" id="please-wait" style="display:none;">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
         alt="<?php echo $this->__('Updating...') ?>" title="<?php echo $this->__('Updating...') ?>"
         class="v-middle"/> <?php echo $this->__('Updating...') ?>
</span>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo Mage::getUrl('customer/account/'); ?>">
            <small>&#171;</small> <?php echo $this->__("Back") ?></a></p>
</div>

<script type="text/javascript">
    //<![CDATA[
    var regionsJson =
        <?php echo $this->helper('directory')->getRegionJson() ?>
        ;
    // Ajax call request timeout in ms
    var ajaxTimeout = 10000;
    //]]>
</script>
