<?php $itemType = $this->getItemType() ?>

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
        	<?php 
        		$page = Mage::getModel('pagemanager/page')->getPage($_SESSION['page_id']);
        	?>
            <td><h3><?php echo $this->__('Add image to page: ').$page['name']?></h3></td>
            <td class="a-right">
            	<?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="addimage_form" enctype="multipart/form-data" name="addimage_form" method="post" action="<?php echo $this->getUrl('*/*/saveimage')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <input name="addimageform[type]" type="hidden" value="<?php echo $itemType['value'] ?>" />
        <input name="addimageform[row_id]" type="hidden" value="<?php echo $this->getRequest()->getParam('id') ?>" />
        <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Enter the image information below')?></h4></div>
        <fieldset id="my-fieldset" class="fieldset-wide">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Image')?> <span class="required">*</span></td>
                    <td class="value"><input class="input-file required-entry" type="file" name="file" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Title')?> <span class="required">*</span></td>
                    <td class="value"><input class="input-text required-entry" name="addimageform[title]" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Image text')?></td>
                    <td class="value"><textarea id="pagemanager-image-text" class="input-text" name="addimageform[image_text]" style="width:200px;height:100px;"></textarea></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Alt-text')?></td>
                    <td class="value"><input class="input-text" name="addimageform[image_alt]" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Link')?></td>
                    <td class="value"><input class="input-text" name="addimageform[link]" /></td>
                </tr> 
                <tr>
                    <td class="label"><?php echo $this->__('Link target')?></td>
                    <td class="value">
                    	<select name="addimageform[link_target]">
                    		<option value=""><?php echo $this->__('Same window'); ?></option>
                    		<option value="_blank"><?php echo $this->__('New window'); ?></option>
                    	</select>
                   	</td>
                </tr>   
                <tr>
                    <td class="label"><?php echo $this->__('Status')?> <span class="required">*</span></td>
                    <td class="value">
                    	<select name="addimageform[status]">
                    		<?php $statuses = Mage::helper('pagemanager')->getStatuses(); ?>
                    		<?php foreach($statuses as $key => $title): ?>
	                    		<option value="<?php echo $key?>"><?php echo $this->__($title)?></option>
                    		<?php endforeach; ?>
                    	</select>
                    </td>
                </tr>    
                <tr>
                    <td class="label"><?php echo $this->__('Position')?></td>
                    <td class="value"><input class="input-text" name="addimageform[position]" style="width:30px;" /></td>
                </tr>            
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var addimageForm = new varienForm('addimage_form');
</script>
