<?php
/**
 * Sweet Tooth
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Sweet Tooth SWEET TOOTH POINTS AND REWARDS
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth License is available at this URL:
 *     https://www.sweettoothrewards.com/terms-of-service
 * The Open Software License is available at this URL:
 *      http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * By adding to, editing, or in any way modifying this code, Sweet Tooth is
 * not held liable for any inconsistencies or abnormalities in the
 * behaviour of this code.
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by Sweet Tooth, outlined in the
 * provided Sweet Tooth License.
 * Upon discovery of modified code in the process of support, the Licensee
 * is still held accountable for any and all billable time Sweet Tooth spent
 * during the support process.
 * Sweet Tooth does not guarantee compatibility with any other framework extension.
 * Sweet Tooth is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to
 * support@sweettoothrewards.com or call 1.855.699.9322, so we can send you a copy
 * immediately.
 *
 * @category   [TBT]
 * @package    [TBT_Rewards]
 * @copyright  Copyright (c) 2014 Sweet Tooth Inc. (http://www.sweettoothrewards.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/**
 * Admin Order Create Search Product View Earning Points
 *
 * @category   TBT
 * @package    TBT_Rewards
 * @author     Sweet Tooth Inc. <support@sweettoothrewards.com>
 */
?>
<div class="divider"></div>
<div class="distri_section">
    <?php foreach ($this->getDistriRewards() as $reward_currency => $reward_amount): ?>
        <?php $points_summary = $this->getPointsString($reward_amount, $reward_currency); ?>
        <?php if ($this->doGraphicalEarning()): ?>
            <div class="earnable" align="left">
                <table border=0 cellspacing=0 cellpadding=0><tbody><tr>
                            <td align="left" class="rewards-mini-icon-holder">
                                <img src="<?php echo $this->getSkinUrl("images/rewards/add_points.png", array('_area' => 'frontend')); ?>">
                            </td>
                            <td align="left">
                                <?php if ($this->isBundle()): ?>
                                    <?php echo $this->__('Earn as much as %s for buying this product', $points_summary); ?>
                                <?php elseif ($this->getShowEarningFrom()) : ?>
                                    <?php echo $this->__('Earn starting from %s for buying this product', $points_summary); ?>
                                <?php else :?>
                                    <?php echo $this->__('You will earn %s for buying this product', $points_summary); ?>
                                <?php endif; ?>
                            </td>
                        </tr></tbody></table>
            </div>
        <?php else: ?>
            <div class="you_will_earn rewards-caption-text rewardsCatalogYouWillEarn">
                <?php if ($this->getShowEarningFrom()) : ?>
                    <?php echo $this->__('Earn starting from %s for buying this product', $points_summary); ?>
                <?php else :?>
                    <?php echo $this->__('You will earn %s for buying this product', $points_summary); ?>
                <?php endif; ?>
            </div>
        <?php endif ?>

        <?php /* $reward_currency is almost always '1' and $reward_amount is an integer amount of points to display. */ ?>
        <?php $img_url = $this->getPointsImgUrl($reward_amount, $reward_currency); ?>
        <?php $imgPath = Mage::getSingleton('rewards/currency')->load($reward_currency)->getImage(); ?>
        <?php if (!empty($imgPath)): ?>
            <img src="<?php echo $img_url; ?>" class="points_image points_currency_image-<?php echo $reward_currency ?>"/>
        <?php endif; ?>
    <?php endforeach; ?>
</div>