<?php
/**
 * Copyright (c) 2009-2012 Vaimo AB
*
* Vaimo reserves all rights in the Program as delivered. The Program
* or any portion thereof may not be reproduced in any form whatsoever without
* the written consent of Vaimo, except as provided by licence. A licence
* under Vaimo's rights in the Program may be available directly from
* Vaimo.
*
* Disclaimer:
* THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
* THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
* THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
* IN THE PROGRAM.
*
* @category    Icommerce
* @package     Icommerce_SlideshowManager
* @copyright   Copyright (c) 2009-2012 Vaimo AB
*/
?>

<?php
  /** @var Icommerce_SlideshowManager_Helper_Data $helper */
  $helper = Mage::helper('slideshowmanager');

	// Load images
  $items = $this->getSlideshowItems($this->getSlideshowId());
?>

<?php if(is_array($items) && count($items) > 0): ?>
<ul>
<?php

	/** The $item variable contains the following keys
	 * ------------------------------------------------
	 * $item['id']
	 * $item['slideshow_id']
	 * $item['filename']
	 * $item['image_alt']
	 * $item['title']
	 * $item['image_text']
	 * $item['link']
	 * $item['link_target']
	 * $item['status']
	 * $item['created_on']
	 * $item['created_by']
	 * $item['position']
	*/

	foreach($items as $item):
		if($item['type'] == 'html'):
			echo '<li>'.Icommerce_Cms::processBlockDirectives($item['slideshow_content']).'</li>';
		else:
			echo '<li><img src="'.$helper->getImageUrl($item).'" alt="'.$item['image_alt'].'" /></li>';
		endif;
	endforeach;
?>
</ul>
<?php endif; ?>