<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Menu
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */
$menu = $this->renderMenu();
?>
<?php if ($menu): ?>
    <div class="nav-container">
        <div class="row">
            <ul id="nav"
                class="clearfix col-xs-12 col-sm-12 col-md-12 col-lg-12 <?php echo $this->getMenuTypeClass() ?>">
                <?php echo $menu ?>
                <li class="hidden-inline-block-xs hidden-inline-block-sm menu-search">
                    <div class="search-wrapper">
                        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalogsearch/form.mini.phtml')->toHtml() ?>
                    </div>
                </li>
                <li class="menu-cms-block visible-inline-block-xs visible-inline-block-sm">
                    <?php echo $this->getLayout()->createBlock('cms/block',
                        'menu_bottom_block_mobile')->setBlockId('menu_bottom_block_mobile')->toHtml() ?>
                </li>
            </ul>
        </div>
    </div>
    <div id="menu-overlay"></div>
<?php endif;
