<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Menu
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */
 
$_categoryLevel = $this->getCategory()->getLevel();
$_bold = $this->getCategory()->getBold();
$_disabledLink = $this->getCategory()->getDisableLink();
$_itemUrl = ($_disabledLink) ? '#' : $this->getItemUrl();
$_menuImage = $this->getCategory()->getMenuImage();
?>

<?php if ($this->shouldShowLink() || $this->shouldShowChildren()):?>
    <li class="<?php echo $this->getMenuItemClass() ?> <?php echo ($_disabledLink) ? 'disabled-item' : '';?> <?php echo $this->hasWidget('menu_widget') ? 'menu-widget-container' : '';?>">
        <?php if ($this->shouldShowLink()): ?>
            <?php // moved before link due to resizing some-times hiding the buttons -- might be a browser glitch ?>
            <?php if ($this->shouldShowChildren()): ?>
                <button class="toggle-sub-menu"><i class="fal <?php echo ($this->isInCurrentPath()) ? 'fa-angle-down' : 'fa-angle-right';?>"></i><span class="sr-only"><?php echo $this->__('Toggle') ?></span></button>
            <?php endif; ?>
            
            <a href="<?php echo $_itemUrl ?>" class="<?php echo $this->getLinkClass() ?> <?php echo ($_disabledLink) ? 'disabled-link' : '';?> <?php echo ($_bold) ? 'bold' : '';?> <?php echo ($_menuImage) ? 'image' : '';?>">
                <span class="label<?php if ($_menuImage): ?> desktop<?php endif; ?>"><?php echo $this->getItemLabel() ?></span>
                <?php if ($_menuImage):?>
                    <span class="menu-image-container">
                        <img src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' . $_menuImage;?>" />
                    </span>
                    <span class="label mobile"><?php echo $this->getItemLabel() ?></span>
                <?php endif; ?>
            </a>

            <?php if ($this->hasWidget('menu_widget')): ?>
                <ul class="menu-widget">
                    <li class="<?php echo $this->getItemPlacementClass(true) ?> widget-column">
                        <?php echo $this->getWidgetHtml('menu_widget') ?>
                    </li>
                </ul>
            <?php endif ?>
            
            <?php echo $this->getChildHtmlByLevel('menu.item.after.link') ?>
        <?php endif ?>
        <?php if ($this->shouldShowChildren()): ?>
            <ul class="<?php echo $this->getChildListClass() ?>">
                <?php echo $this->renderChildren('main') ?>
                <?php echo $this->renderGroupChildren('footer') ?>
            </ul>
        <?php endif ?>
    </li>
<?php endif;?>
