<?php
/**
 * Copyright (c) 2009-2016 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Hylete
 * @copyright   Copyright (c) 2009-2016 Vaimo AB
 * @author      Giorgos Tsioutsiouliklis <giorgos@vaimo.com>
 */
?>

<?php
$customer = Mage::getSingleton('customer/session')->getCustomer();

if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <a class="account-button logged-in" href="<?php echo $this->getUrl('customer/account');?>">
        <span class="hidden-inline-block-xs hidden-inline-block-sm welcomeTextNormalHeader"><?php echo $this->escapeHtml($customer->getFirstname()) ?></span>
    </a>
<?php else:?>
    <a class="account-button" href="<?php echo $this->getUrl('customer/account/login');?>">
        <span class="hidden-inline-block-xs hidden-inline-block-sm"><?php echo $this->__('log in / join');?></span>
    </a>
<?php endif;?>