<html><head></head><body>

	<div style="text-align: center; height: 400px; vertical-align: middle; padding-top: 140px;">
		<div style="font-family: Arial; font-size: 11px; margin-bottom: 20px;"><?php echo $this->__('Aborting Dibs payment.') ?></div>
		<img style="border: 0px;" src="<?php echo $this->getSkinUrl('images/dibs/redirect-loader.gif') ?>">
  </div>

  <script language="javascript">
		// If payment aborted we redirect to failure page.
  	this.parent.parent.window.location = '<?php echo $this->getDibs()->getFinalFailureURL() ?>';
  </script>

</body></html>
