<?php
/**
 * Copyright (c) 2009-2017 Vaimo Group
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Cms
 * @copyright   Copyright (c) 2009-2017 Vaimo Group
 */
?>
<?php if ($calls = $this->getClassInstantiationCalls()): ?>
    <?php if (!$this->getIsNestedLibrary()): ?>
    <script type="application/javascript">
        (function($){
            "use strict";
    <?php endif ?>
        <?php foreach ($this->getChild() as $child): ?>
            <?php $child->setIsNestedLibrary(true); ?>
            <?php echo $child->toHtml() ?>
        <?php endforeach ?>


        <?php foreach ($calls as $variable => $data): ?>
    <?php echo $this->_getInstantiationCall("var %s = $.%s(%s);", current($data), 20); ?>
        <?php array_shift($data) ?>
        <?php foreach ($data as $call): ?>
        <?php echo $this->_getFunctionCall(key($call), current($call)); ?>
        <?php endforeach ?>
        <?php endforeach ?>
    <?php if (!$this->getIsNestedLibrary()): ?>

        })(jQuery);
    </script>
    <?php endif ?>
<?php endif ?>
