<?php $itemType = $this->getItemType() ?>

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
        	<?php 
        		$page = Mage::getModel('pagemanager/page')->getPage($_SESSION['page_id']);
        	?>
            <td><h3><?php echo $this->__('Add toplist to page: ').$page['name']?></h3></td>
            <td class="a-right">
            	<?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="addtoplist_form" enctype="multipart/form-data" name="addtoplist_form" method="post" action="<?php echo $this->getUrl('*/*/savetoplist')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <input name="addtoplistform[type]" type="hidden" value="<?php echo $itemType['value'] ?>" />
        <input name="addtoplistform[row_id]" type="hidden" value="<?php echo $this->getRequest()->getParam('id') ?>" />
        <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Enter the toplist information below')?></h4></div>
        <fieldset id="my-fieldset" class="fieldset-wide">
            <table cellspacing="0" class="form-list">
            	<tr>
                    <td class="label"><?php echo $this->__('Title')?> <span class="required">*</span></td>
                    <td class="value"><input class="input-text required-entry" name="addtoplistform[title]" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Category id')?></td>
                    <td class="value"><input class="input-text" name="addtoplistform[category_id]" /></td>
                </tr>
                <?php /*<tr>
                    <td class="label"><?php echo $this->__('Number of products per row')?> </td>
                    <td class="value"><input class="input-text" name="addtoplistform[products_per_row]" /></td>
                </tr> */ ?>
                <tr>
                    <td class="label"><?php echo $this->__('Total number of products')?></td>
                    <td class="value"><input class="input-text" name="addtoplistform[total_products]" /></td>
                </tr>
                <tr>
                	<td class="label"><?php echo $this->__('Choose toplist style')?> <span class="required">*</span></td>
                	<td class="value">
	                   	<select name="addtoplistform[toplist]">
	                    	<?php $toplistOptions = Mage::helper('pagemanager')->getToplistOptions(); ?>
	                    	<?php foreach($toplistOptions as $key => $title): ?>
		                    	<option value="<?php echo $title['value']?>"><?php echo $this->__($title['label'])?></option>
	                    	<?php endforeach; ?>
	                    </select>
                    </td>
                </tr>                
                <tr>
                	<td class="label"><?php echo $this->__('Sort by')?> <span class="required">*</span></td>
                	<td class="value">
	                   	<select name="addtoplistform[sort_by]">
	                    	<?php $sortOptions = Mage::helper('pagemanager')->getSortOptions(); ?>
	                    	<?php foreach($sortOptions as $key => $title): ?>
		                    	<option value="<?php echo $title['value']?>"><?php echo $this->__($title['label'])?></option>
	                    	<?php endforeach; ?>
	                    </select>
                    </td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Status')?> <span class="required">*</span></td>
                    <td class="value">
                    	<select name="addtoplistform[status]">
                    		<?php $statuses = Mage::helper('pagemanager')->getStatuses(); ?>
                    		<?php foreach($statuses as $key => $title): ?>
	                    		<option value="<?php echo $key?>"><?php echo $this->__($title)?></option>
                    		<?php endforeach; ?>
                    	</select>
                    </td>
                </tr>    
                <tr>
                    <td class="label"><?php echo $this->__('Position')?></td>
                    <td class="value"><input class="input-text" name="addtoplistform[position]" style="width:30px;" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Manual products ids')?></td>
                    <td class="value"><input class="input-text" name="edittoplistform[product_ids]" style="width:30px;" value=""/>
                        <br>Select "sort by" manual products. Add comma separated list of product ids to override.
                    </td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var addtoplistForm = new varienForm('addtoplist_form');
</script>
