<!--

/**
 * @author    Mediotype Development <diveinto@mediotype.com>
 * @copyright 2018 Mediotype. All Rights Reserved.
 */

-->
<div class="modals-wrapper">
    <aside role="dialog" class="modal-slide mcs-register-form-slide _inner-scroll"
           aria-labelledby="modal-title-0" aria-describedby="modal-content-0" data-role="modal" data-type="slide"
           tabindex="0">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" data-role="focusable-scope">
            <header class="modal-header">
                <h1 id="modal-title-0" class="modal-title" data-role="title">
                    <?php echo $this->__('Registeration') ?>
                </h1>
                <a class="action-close"><span class="sprite-close "></span></a>
            </header>
            <div id="modal-content-0" class="modal-content" data-role="content">
                <div id="mcs-ajaxRegisterForm" class="mcs-ajaxRegisterForm">
                    <div class="register-messages">
                        <div class="message"></div>
                    </div>
                    <?php echo $this->getChildHtml('signup_form') ?>
                    <br>
                </div>
            </div>
        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>

    <aside role="dialog" class="modal-slide mcs-forgetpassword-form-slide _inner-scroll"
           aria-labelledby="modal-title-1" aria-describedby="modal-content-1" data-role="modal" data-type="slide"
           tabindex="0">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" data-role="focusable-scope">
            <header class="modal-header">
                <h1 id="modal-title-1" class="modal-title"
                    data-role="title"><?php echo $this->__('Forget Password') ?></h1>
                <a class="action-close"><span class="sprite-close "></span></a>
            </header>
            <div id="modal-content-1" class="modal-content" data-role="content">
                <div id="mcs-ajaxForgetPasswordForm" class="mcs-ajaxForgetPasswordForm">
                    <div class="forgetpassword-messages">
                        <div class="message"></div>
                    </div>
                    <form class="form password forget mcs-forget-password-form-success-hide"
                          action="<?php echo $this->getUrl('ajaxlogin/ajax/forgotpassword'); ?>"
                          method="post" id="mcs-form-forget-reset" novalidate="novalidate">
                        <?php echo $this->getBlockHtml('formkey')?>
                        <fieldset class="fieldset" data-hasrequired="* Required Fields">
                            <div class="field note"><?php echo $this->__('Please enter your email address below to receive a password reset
                                link.') ?>
                            </div>
                            <div class="field email required">
                                <label for="email_addressforget"
                                       class="label"><span><?php echo $this->__('Email') ?></span></label>
                                <div class="control">
                                    <input type="email" name="email" alt="email" id="email_addressforget"
                                           class="input-text  validate-email required-entry"
                                           value=""
                                           aria-required="true">
                                </div>
                            </div>
                        </fieldset>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action submit primary">
                                    <span><?php echo $this->__('Reset My Password') ?></span>
                                </button>
                            </div>
                            <div class="secondary">
                                <span class="action back"
                                      onclick="AjaxLogin.toLogin()"><?php echo $this->__('Go back') ?></span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>

    <aside role="dialog" class="modal-slide mcs-login-form-slide  _inner-scroll "
           aria-labelledby="modal-title-4" aria-describedby="modal-content-4 " id="mcs-login-form-slide"
           data-role="modal" data-type="slide"
           tabindex="0">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" id="login-form" data-role="focusable-scope">
            <header class="modal-header">
                <h1 id="modal-title-4" class="modal-title" data-role="title">
                    <?php echo $this->__('Login') ?>
                </h1>
                <a class="action-close"><span class="sprite-close "></span></a>
            </header>

            <div id="modal-content-4" class="modal-content" data-role="content">
                <div id="mcs-ajaxloginForm" class="mcs-ajaxloginForm">
                    <div id="mcs-loginForm">
                        <div class="login-messages">
                            <div class="message"></div>
                        </div>
                        <form class="form form-login"
                              action="<?php echo $this->getUrl('ajaxlogin/ajax/login'); ?>"
                              method="post" id="mcs-form-login" novalidate="novalidate">
                            <?php echo $this->getBlockHtml('formkey')?>
                            <?php if (!Mage::getStoreConfig('general/restriction/is_active') || Mage::getStoreConfig('general/restriction/mode') == 2):?>
                                <div class="new-users">
                                    <h2><?php echo $this->__('#HYLETEnation') ?></h2>
                                    <div class="login-block">
                                        <div class="content">
                                            <?php echo $this->getLayout()->createBlock('cms/block', 'login_page_hyletenation')->setBlockId('login_page_hyletenation')->toHtml() ?>
                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-12">
                                            <button type="button" title="<?php echo $this->__('join the #HYLETEnation') ?>" class="button hyletenation-btn" onclick="AjaxLogin.toRegistration()"><span><span><?php echo $this->__('join the #HYLETEnation') ?></span></span></button>
                                        </div>
                                    </div>
                                    <?php if (Mage::getStoreConfig('sociallogin/facebook/activate')):?>
                                        <div class="links visible-xs visible-sm">
                                            <p class="align-center"><a onclick="return facebookPopup();" class="facebook-login"><i class="fab fa-facebook-f"></i><?php echo $this->__('log in with Facebook');?></a></p>
                                        </div>
                                    <?php endif;?>
                                </div>
                            <?php endif;?>

                            <div class="login-container visible-xs visible-sm">
                                <h2><?php echo $this->__('Already a member? Log in below'); ?></h2>
                            </div>

                            <fieldset class="fieldset login" data-hasrequired="* Required Fields">
                                <div class="field email required">
                                    <label class="label" for="email">
                                        <span><?php echo $this->__('Email') ?></span></label>
                                    <div class="control">
                                        <input name="username" value="" autocomplete="off" id="email" type="email"
                                               class="input-text input-text required-entry validate-email" title="Email"
                                        ">
                                    </div>
                                </div>
                                <div class="field password required">
                                    <label for="pass" class="label">
                                        <span><?php echo $this->__('Password') ?></span>
                                    </label>
                                    <div class="control">
                                        <input name="password" type="password" autocomplete="off"
                                               class="input-text input-text required-entry validate-password"
                                               id="pass" title="Password">
                                    </div>
                                </div>
                                <div class="actions-toolbar">
                                    <input name="context" type="hidden" value="checkout">
                                    <div class="primary">
                                        <button type="submit" class="action login primary" name="send" id="send2">
                                            <span><?php echo $this->__('Login') ?></span>
                                        </button>
                                    </div>
                                    <div class="secondary"><span class="action reset-password-btn remind"
                                                                 onclick="AjaxLogin.toResetPassword()"><span>
                                                <?php echo $this->__('Forgot Your Password?') ?></span></span>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>

                </div>
            </div>
        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>

    <aside role="dialog" class="modal-slide mcs-logout-slide
               _inner-scroll" aria-labelledby="modal-title-2" aria-describedby="modal-content-2" data-role="modal"
           data-type="slide" tabindex="0">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" data-role="focusable-scope">
            <header class="modal-header">
                <h1 id="modal-title-2" class="modal-title" data-role="title"><?php echo $this->__('Logout') ?></h1>
                <a class="action-close"><span class="sprite-close "></span></a>
            </header>
            <div id="modal-content-2" class="modal-content" data-role="content">
                <div id="mcs-ajaxLogout" class="mcs-ajaxLogout">
                    <div class="messages">
                        <ul class="messages">
                            <li class="success-msg">
                                <ul>
                                    <li><span><?php echo $this->__('Successfully logged out'); ?></span></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>

    <div class="modals-overlay" style="display: none;"></div>

    <div data-role="loader" class="loading-mask" id="mcs-custom-loader" style="display: none;">
        <div class="loader">
            <img src="<?php echo $this->getSkinUrl('images/mediotype/loader-1.gif') ?>" alt="Loading...">
        </div>
    </div>

    <script type="text/javascript">
        var loginForm = new VarienForm('mcs-form-login', true),
            registrationForm = new VarienForm('mcs-form-register', true),
            forgetForm = new VarienForm('mcs-form-forget-reset', true);
    </script>
</div>