<!--

/**
 * @author    Mediotype Development <diveinto@mediotype.com>
 * @copyright 2018 Mediotype. All Rights Reserved.
 */

-->
<script src="https://www.google.com/recaptcha/api.js?render=6LfKHLIUAAAAACn-USCuObJmm5F3cPJCxsHwdeSN"></script>
<script>
    grecaptcha.ready(function () {
        grecaptcha.execute('6LfKHLIUAAAAACn-USCuObJmm5F3cPJCxsHwdeSN', { action: 'login' })
            .then(function (token) {
                var recaptchaResponse = document.getElementById('recaptchaLoginResponse');
                recaptchaResponse.value = token;
            });
    });
</script>

<div class="modals-wrapper">
    <aside role="dialog" class="modal-slide mcs-register-form-slide _inner-scroll"
           aria-labelledby="modal-title-0" aria-describedby="modal-content-0" data-role="modal" data-type="slide"
           tabindex="0">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" data-role="focusable-scope">
            <header class="modal-header">
                <div class="header-wrap">
                    <div class="title"><?php echo $this->__('Create Account') ?></div>
                </div>
                <a class="action-close"><svg viewBox="0 0 60 60">
                        <path d="M35.7,30L58.8,6.8C59.6,6.1,60,5.1,60,4c0-2.2-1.8-4-4-4c-1.1,0-2.1,0.4-2.8,1.2L30,24.3
        L6.8,1.2C6.1,0.4,5.1,0,4,0C1.8,0,0,1.8,0,4c0,1.1,0.4,2.1,1.2,2.8L24.3,30L1.2,53.2C0.4,53.9,0,54.9,0,56c0,2.2,1.8,4,4,4
        c1.1,0,2.1-0.4,2.8-1.2L30,35.7l23.2,23.2c0.7,0.7,1.7,1.2,2.8,1.2c2.2,0,4-1.8,4-4c0-1.1-0.4-2.1-1.2-2.8L35.7,30z"></path>
                    </svg></a>
            </header>
            <div id="modal-content-0" class="modal-content" data-role="content">
                <div id="mcs-ajaxRegisterForm" class="mcs-ajaxRegisterForm">
                    <div class="register-messages">
                        <div class="message"></div>
                    </div>
                    <div class="login-container">
                        <?php echo $this->getLayout()->createBlock('cms/block', 'registration_page_hyletenation_top')->setBlockId('registration_page_hyletenation_top')->toHtml() ?>
                    </div>
                    <?php echo $this->getChildHtml('signup_form') ?>
                    <br>
                </div>
            </div>
        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>

    <aside role="dialog" class="modal-slide mcs-forgetpassword-form-slide _inner-scroll"
           aria-labelledby="modal-title-1" aria-describedby="modal-content-1" data-role="modal" data-type="slide"
           tabindex="0">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" data-role="focusable-scope">
            <header class="modal-header">
                <div class="header-wrap">
                    <div class="title"><?php echo $this->__('Reset Password') ?></div>
                </div>
                <a class="action-close"><svg viewBox="0 0 60 60">
                        <path d="M35.7,30L58.8,6.8C59.6,6.1,60,5.1,60,4c0-2.2-1.8-4-4-4c-1.1,0-2.1,0.4-2.8,1.2L30,24.3
        L6.8,1.2C6.1,0.4,5.1,0,4,0C1.8,0,0,1.8,0,4c0,1.1,0.4,2.1,1.2,2.8L24.3,30L1.2,53.2C0.4,53.9,0,54.9,0,56c0,2.2,1.8,4,4,4
        c1.1,0,2.1-0.4,2.8-1.2L30,35.7l23.2,23.2c0.7,0.7,1.7,1.2,2.8,1.2c2.2,0,4-1.8,4-4c0-1.1-0.4-2.1-1.2-2.8L35.7,30z"></path>
                    </svg></a>
            </header>
            <div id="modal-content-1" class="modal-content" data-role="content">
                <div id="mcs-ajaxForgetPasswordForm" class="mcs-ajaxForgetPasswordForm">
                    <div class="forgetpassword-messages">
                        <div class="message"></div>
                    </div>
                    <form class="form password forget mcs-forget-password-form-success-hide"
                          action="<?php echo $this->getUrl('ajaxlogin/ajax/forgotpassword'); ?>"
                          method="post" id="mcs-form-forget-reset" novalidate="novalidate">
                        <?php echo $this->getBlockHtml('formkey')?>
                        <fieldset class="fieldset" data-hasrequired="* Required Fields">
                            <div class="field note"><?php echo $this->__('Please enter your email address below to receive a password reset
                                link.') ?>
                            </div>
                            <div class="field email required">
                                <label for="email_addressforget"
                                       class="label"><span><?php echo $this->__('Email') ?></span><span class="required">*</span></label>
                                <div class="control">
                                    <input type="email" name="email" alt="email" id="email_addressforget"
                                           class="input-text  validate-email required-entry"
                                           value=""
                                           aria-required="true">
                                </div>
                            </div>
                        </fieldset>
                        <div class="actions-toolbar">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="primary">
                                        <button type="submit" class="action submit primary">
                                            <span><?php echo $this->__('Reset My Password') ?></span>
                                        </button>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="secondary">
                                        <a class="action back"
                                           onclick="AjaxLogin.toLogin()"><?php echo $this->__('Go back') ?></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>

    <aside role="dialog" class="modal-slide mcs-login-form-slide  _inner-scroll "
           aria-labelledby="modal-title-4" aria-describedby="modal-content-4 " id="mcs-login-form-slide"
           data-role="modal" data-type="slide"
           tabindex="0">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" id="login-form" data-role="focusable-scope">
            <header class="modal-header">
                <div class="header-wrap">
                    <div class="title"><?php echo $this->__('Login') ?></div>
                </div>
                <a class="action-close"><svg viewBox="0 0 60 60">
                        <path d="M35.7,30L58.8,6.8C59.6,6.1,60,5.1,60,4c0-2.2-1.8-4-4-4c-1.1,0-2.1,0.4-2.8,1.2L30,24.3
        L6.8,1.2C6.1,0.4,5.1,0,4,0C1.8,0,0,1.8,0,4c0,1.1,0.4,2.1,1.2,2.8L24.3,30L1.2,53.2C0.4,53.9,0,54.9,0,56c0,2.2,1.8,4,4,4
        c1.1,0,2.1-0.4,2.8-1.2L30,35.7l23.2,23.2c0.7,0.7,1.7,1.2,2.8,1.2c2.2,0,4-1.8,4-4c0-1.1-0.4-2.1-1.2-2.8L35.7,30z"></path>
                    </svg></a>
            </header>
            <div id="modal-content-4" class="modal-content" data-role="content">
                <div id="mcs-ajaxloginForm" class="mcs-ajaxloginForm">
                    <div id="mcs-loginForm">
                        <div class="login-messages">
                            <div class="message"></div>
                        </div>
                        <div id="login-form">
                            <form class="form form-login"
                                  action="<?php echo $this->getUrl('ajaxlogin/ajax/login'); ?>"
                                  method="post" id="mcs-form-login" novalidate="novalidate">
                                <input type="hidden" value="" name="recaptcha_response" id="recaptchaLoginResponse">
                                <?php echo $this->getBlockHtml('formkey')?>

                                <div class="login-container">
                                    <?php echo $this->getLayout()->createBlock('cms/block', 'login_page_hyletenation_top')->setBlockId('login_page_hyletenation_top')->toHtml() ?>
                                </div>

                                <fieldset class="fieldset login" data-hasrequired="* Required Fields">
                                    <div class="field email control required">
                                        <label class="label" for="email">
                                            <span><?php echo $this->__('Email') ?></span><span class="required">*</span></label>
                                        <div class="control">
                                            <input name="username" value="" autocomplete="off" id="email" type="email"
                                                   class="input-text input-text required-entry validate-email" title="Email">
                                        </div>
                                    </div>
                                    <div class="field control password required">
                                        <label for="pass" class="label">
                                            <span><?php echo $this->__('Password') ?></span><span class="required">*</span>
                                        </label>
                                        <div class="control">
                                            <input name="password" type="password" autocomplete="off"
                                                   class="input-text input-text required-entry validate-password"
                                                   id="pass" title="Password">
                                        </div>
                                    </div>
                                    <div class="actions-toolbar">
                                        <div class="row">
                                            <div class="col-xs-6">
                                                <div class="primary">
                                                    <button type="submit" class="action login primary" name="send" id="send2">
                                                        <span><?php echo $this->__('Log in') ?></span>
                                                    </button>
                                                </div>
                                                <p><?php echo $this->__('or') ?></p>
                                                <div class="links">
                                                    <?php if (Mage::getStoreConfig('sociallogin/facebook/activate')):?>
                                                        <a onclick="return facebookPopup();" class="facebook-login"><i class="fab fa-facebook-f"></i><?php echo $this->__('FACEBOOK LOGIN');?></a>
                                                    <?php endif;?>
                                                </div>
                                            </div>
                                            <div class="col-xs-6">
                                                <div class="secondary"><a class="action reset-password-btn remind"
                                                                          onclick="AjaxLogin.toResetPassword()"><span>
                                                <?php echo $this->__('Forgot Your Password?') ?></span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php if (!Mage::getStoreConfig('general/restriction/is_active') || Mage::getStoreConfig('general/restriction/mode') == 2):?>
                                        <div class="new-users">
                                            <div class="login-block">
                                                <div class="content">
                                                    <?php echo $this->getLayout()->createBlock('cms/block', 'login_page_hyletenation')->setBlockId('login_page_hyletenation')->toHtml() ?>
                                                </div>
                                                <div class="col-xs-12 col-sm-12 col-md-12">
                                                    <button type="button" title="<?php echo $this->__('create account') ?>" class="button hyletenation-btn" onclick="AjaxLogin.toRegistration()"><span><span><?php echo $this->__('Create Account') ?></span></span></button>
                                                </div>
                                            </div>
                                    <?php endif;?>
                                </fieldset>
                            </form>

                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>

    <aside role="dialog" class="modal-slide mcs-logout-slide
               _inner-scroll" aria-labelledby="modal-title-2" aria-describedby="modal-content-2" data-role="modal"
           data-type="slide" tabindex="0">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" data-role="focusable-scope">
            <header class="modal-header">
                <div class="header-wrap">
                    <div class="title"><?php echo $this->__('Logout') ?></div>
                </div>
                <a class="action-close"><svg viewBox="0 0 60 60">
                        <path d="M35.7,30L58.8,6.8C59.6,6.1,60,5.1,60,4c0-2.2-1.8-4-4-4c-1.1,0-2.1,0.4-2.8,1.2L30,24.3
        L6.8,1.2C6.1,0.4,5.1,0,4,0C1.8,0,0,1.8,0,4c0,1.1,0.4,2.1,1.2,2.8L24.3,30L1.2,53.2C0.4,53.9,0,54.9,0,56c0,2.2,1.8,4,4,4
        c1.1,0,2.1-0.4,2.8-1.2L30,35.7l23.2,23.2c0.7,0.7,1.7,1.2,2.8,1.2c2.2,0,4-1.8,4-4c0-1.1-0.4-2.1-1.2-2.8L35.7,30z"></path>
                    </svg></a>
            </header>
            <div id="modal-content-2" class="modal-content" data-role="content">
                <div id="mcs-ajaxLogout" class="mcs-ajaxLogout">
                    <div class="messages">
                        <ul class="messages">
                            <li class="success-msg">
                                <ul>
                                    <li><span><?php echo $this->__('Successfully logged out'); ?></span></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>
    <aside role="dialog" class="modal-slide mcs-nasm-register-form-slide _inner-scroll"
           aria-labelledby="modal-title-3" aria-describedby="modal-content-3" data-role="modal" data-type="slide"
           tabindex="0">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" data-role="focusable-scope">
            <header class="modal-header">
                <div class="header-wrap">
                    <div class="title"><?php echo $this->__('Create Account') ?></div>
                </div>
                <a class="action-close"><svg viewBox="0 0 60 60">
                        <path d="M35.7,30L58.8,6.8C59.6,6.1,60,5.1,60,4c0-2.2-1.8-4-4-4c-1.1,0-2.1,0.4-2.8,1.2L30,24.3
        L6.8,1.2C6.1,0.4,5.1,0,4,0C1.8,0,0,1.8,0,4c0,1.1,0.4,2.1,1.2,2.8L24.3,30L1.2,53.2C0.4,53.9,0,54.9,0,56c0,2.2,1.8,4,4,4
        c1.1,0,2.1-0.4,2.8-1.2L30,35.7l23.2,23.2c0.7,0.7,1.7,1.2,2.8,1.2c2.2,0,4-1.8,4-4c0-1.1-0.4-2.1-1.2-2.8L35.7,30z"></path>
                    </svg></a>
            </header>
            <div id="modal-content-3" class="modal-content" data-role="content">
                <div id="mcs-ajaxRegisterForm" class="mcs-ajaxRegisterForm">
                    <div class="register-messages">
                        <div class="message"></div>
                    </div>
                    <div class="login-container">
                        <?php echo $this->getLayout()->createBlock('cms/block', 'registration_page_hyletenation_top')->setBlockId('registration_page_hyletenation_top')->toHtml() ?>
                    </div>
                    <?php echo $this->getChildHtml('nasm_signup_form') ?>
                    <br>
                </div>
            </div>
        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>

    <div data-role="loader" class="loading-mask" id="mcs-custom-loader" style="display: none;">
        <div class="loader">
            <img src="<?php echo $this->getSkinUrl('images/mediotype/loader-1.gif') ?>" alt="Loading...">
        </div>
    </div>

    <script type="text/javascript">
        var loginForm = new VarienForm('mcs-form-login', true),
            registrationForm = new VarienForm('mcs-form-register', true),
            registrationFormNasm = new VarienForm('mcs-form-register-nasm', true),
            forgetForm = new VarienForm('mcs-form-forget-reset', true);

        // fix custom select
        jQuery(document).ready(function ($) {
            "use strict";

            $('.modals-wrapper select').selectOrDie();
        });

    </script>
</div>
