<!--

/**
 * @author    Mediotype Development <diveinto@mediotype.com>
 * @copyright 2018 Mediotype. All Rights Reserved.
 */

-->
<script>
    grecaptcha.ready(function () {
        grecaptcha.execute('6LfKHLIUAAAAACn-USCuObJmm5F3cPJCxsHwdeSN', { action: 'registration' })
            .then(function (token) {
                var recaptchaResponse = document.getElementById('recaptchaRegistrationResponse');
                recaptchaResponse.value = token;
            });
    });
</script>

<form class="form create account form-create-account"
      action="<?php echo $this->getUrl('ajaxlogin/ajax/create'); ?>"
      method="post" id="mcs-form-register" enctype="multipart/form-data" autocomplete="off"
      novalidate="novalidate">
    <?php echo $this->getBlockHtml('formkey'); ?>

    <fieldset class="fieldset create info">
        <input type="hidden" value="" name="recaptcha_response" id="recaptchaRegistrationResponse">
        <input type="hidden" name="customer_group_id"
               value="<?php echo $this->getCustomerGroupId(); ?>"/>
        <input type="hidden" name="success_url" value="">
        <input type="hidden" name="error_url"
               value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>">
        <input name="form_key" type="hidden"
               value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>

        <h2 class="legend"><?php echo $this->__('Your Name') ?></h2>
        <ul>
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

            <li><?php echo $this->getLayout()->createBlock('customer/widget_gender')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
            </li>
        </ul>
        <h2 class="legend section"><?php echo $this->__('Account Info') ?></h2>
        <label for="email_address" class="required"><?php echo $this->__('Email Address') ?> <span
                    class="required">*</span></label>
        <input type="email" name="email" id="email_address"
               value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>"
               title="<?php echo $this->__('Email Address') ?>"
               class="span4 input-text validate-email required-entry"/>

        <label for="password" class="required"><?php echo $this->__('Password'); ?> <span
                    class="required">*</span></label>
        <input type="password" id="password" name="password"
               class="input-text required-entry validate-password"/>

        <label for="confirmation" class="required"><?php echo $this->__('Confirm Password'); ?>
            <span
                    class="required">*</span></label>
        <input type="password" id="confirmation" name="confirmation"
               class="input-text required-entry validate-cpassword"/>

        <input type="checkbox" id="radiance-lab-create-account-optin-check" name="radiance-lab-create-account-optin-check" value="">
        <label for="radiance-lab-create-account-optin-check"> Optin For Text Alerts</label>
        <div class="radiance-create-account-optin" style="display: none">
            <label for="radiance-lab-create-account-optin" class=""><?php echo $this->__('Enter Your Mobile Number') ?> </label>
            <input type="text" name="radiance-lab-create-account-optin" id="radiance-lab-create-account-optin"
                   value=""
                   title="<?php echo $this->__('Enter Your Mobile Number') ?>"
                   class="span4 input-text "/>
        </div>
        <?php if ($this->isNewsletterEnabled()): ?>
            <input type="hidden" name="is_subscribed" value="1"/>
        <?php endif ?>
        <?php echo $this->getChildHtml('rewards_referral'); ?>

    </fieldset>
    <br>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="Create Account">
                <span><?php echo $this->__('Create Account') ?></span></button>
        </div>
        <p><?php echo $this->__('or') ?></p>
        <div class="links">
            <?php if (Mage::getStoreConfig('sociallogin/facebook/activate')):?>
                <a onclick="return facebookPopup();" class="facebook-login"><i class="fab fa-facebook-f"></i><?php echo $this->__('FACEBOOK LOGIN');?></a>
            <?php endif;?>
        </div>
        <div class="back-to-login">
            <span><?php echo $this->__('Already have an account?') ?></span>
            <a class="action reset-password-btn remind" onclick="AjaxLogin.toLoginFromRegistraion()">
                <span><?php echo $this->__('Log in here') ?></span>
            </a>
        </div>
    </div>
</form>