<?php $id = Mage::getSingleton('core/session')->getGotoadminCategoryId();?>
<?php $path = Mage::getSingleton('core/session')->getGotoadminCategoryPath();?>

<?php if ($id && $path):?>
    <?php Mage::getSingleton('core/session')->setGotoadminCategoryId(false);?>
    <?php Mage::getSingleton('core/session')->setGotoadminCategoryPath(false);?>

    <script>
    Ext.override(Ext.tree.TreePanel, {
        jumpToCategory : function(id)
        {
            var baseUrl = '<?php echo $this->getEditUrl() ?>';
            var urlExt = (this.storeId?'store/'+this.storeId+'/':'')+'id/'+id+'/';
            var url = parseSidUrl(baseUrl, urlExt);
            this.currentNodeId = id;
            if (!this.useAjax) {
                setLocation(url);
                return;
            }
            if (category_info_tabsJsTabs.activeTab) {
                var params = {active_tab_id:category_info_tabsJsTabs.activeTab.id};
            }
            updateContent(url, params);
            this.getNodeById(this.currentNodeId)
        }
    });

    var reloads = 0;
    Ajax.Responders.register({
        onComplete: function(request) {
           if (reloads < 1) {
                reloads++;
    
                tree.expandPath('/<?php echo $path;?>', 'id', function (success, lastNode) {
                    console.log(success);
                    if (success) { 
                        tree.getNodeById(<?php echo $id;?>).select() 
                    }
                });
                
                tree.jumpToCategory(<?php echo $id;?>);
            } 
        }
    });
    </script>
<?php endif;?>