<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SubscribePro
 * @package   SubscribePro_Autoship
 * @author    Subscribe Pro Support <support@subscribepro.com>
 * @copyright 2009-2020 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php
/** @var \SubscribePro\Service\Subscription\SubscriptionInterface $subscription */
$subscription = $this->getSubscription();
/** @var Mage_Catalog_Model_Product $product */
$product = $this->getMagentoProduct();
?>
<div class="subscription-product">
    <?php // Product Image ?>
    <a href="<?php echo $product->getProductUrl() ?>"
       title="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" class="product-image"><img
            src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(80); ?>" width="80" height="80"
            alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"/></a>
    <?php // Product Name ?>
    <?php $_productNameStripped = $this->stripTags($product->getName(), null, true); ?>
    <h2 class="product-name"><a href="<?php echo $product->getProductUrl() ?>"
                                title="<?php echo $_productNameStripped; ?>"><?php echo $product->getName() ?></a></h2>

    <p><span class="product-original-price"><?php echo $this->__("One-Time Purchase Price:") ?> <?php echo $this->getOneTimePurchasePrice(true) ?></span><br/>
        <span class="product-price"><?php echo $this->getSubscriptionPriceText() ?></span></p>
    <?php if (strlen($subscription->getCouponCode())): ?>
        <p><?php echo $this->__("Applied coupon code:") ?> <?php echo $subscription->getCouponCode() ?></p>
    <?php endif; ?>
</div>
