<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SubscribePro
 * @package   SubscribePro_Autoship
 * @author    Subscribe Pro Support <support@subscribepro.com>
 * @copyright 2009-2020 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php
/** @var \SubscribePro\Service\Subscription\SubscriptionInterface $subscription */
$subscription = $this->getSubscription();
/** @var \SubscribePro\Service\Product\ProductInterface $platformProduct */
$platformProduct = $this->getSubscribeProProduct();
$qty = $subscription->getQty();
$intervals = $this->getIntervals();
?>
<div class="subscription-info">
    <form class="interval" action="<?php echo Mage::getUrl('autoship/mysubscriptions/change', array('_secure' => true)) ?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <?php if ($subscription->getStatus() == 'Active' && $subscription->getNextOrderDate() >= date('Y-m-d', strtotime('+1 days'))
        ): ?>
            <p><?php echo $this->__("Next Ship Date:") ?></p>
            <?php // Only allow change of next ship date if its more than N days in the future ?>
            <div class="input-box">
                <input type="text" id="delivery_date_<?php echo $subscription->getId() ?>"
                       name="delivery_date"
                       value="<?php echo $this->getNextOrderDateText() ?>"
                       title="<?php echo $this->__('Next Ship Date:') ?>" class="input-text delivery_date"/>
            </div>
        <?php
        elseif ($subscription->getStatus() == 'Active' && $subscription->getNextOrderDate() < date('Y-m-d', strtotime('+1 days'))
        ): ?>
            <p><?php echo $this->__("Next Ship Date:") ?></p>
            <p><span class="next-order-date"><strong><?php echo $this->getNextOrderDateText() ?></strong></span></p>
        <?php
        elseif ($subscription->getStatus() == 'Paused'): ?>
            <p><span class="status"><strong><?php echo $this->__('Paused') ?></strong></span></p>
        <?php
        elseif ($subscription->getStatus() == 'Failed' || $subscription->getStatus() == 'Retry'): ?>
            <!--<p><span class="status"><strong><?php echo $this->__('Order Issue') ?></strong></span></p>-->
        <?php endif; ?>
        <p>
            <input type="hidden" name="subscription_id" id="subscription_id_<?php echo $subscription->getId() ?>"
                   value="<?php echo $subscription->getId() ?>"/>
            <select id="delivery_qty_<?php echo $subscription->getId() ?>"
                    name="delivery_qty" class="delivery_qty" title="Quantity">
                <?php if ($qty < $platformProduct->getMinQty()): ?>
                    <option value="<?php echo $qty ?>" selected="selected"><?php echo $qty ?></option>
                <?php endif; ?>
                <?php for ($i = $platformProduct->getMinQty(); $i <= $platformProduct->getMaxQty(); $i++): ?>
                    <option value="<?php echo $i ?>"
                            <?php if ($qty == $i): ?>selected="selected"<?php endif; ?>><?php echo $i ?></option>
                <?php endfor; ?>
                <?php if ($qty > $platformProduct->getMaxQty()): ?>
                    <option value="<?php echo $qty ?>" selected="selected"><?php echo $qty ?></option>
                <?php endif; ?>
            </select>
            <?php echo $this->__("unit(s) every") ?>
            <select id="delivery_interval_<?php echo $subscription->getId() ?>"
                    name="delivery_interval" class="delivery_interval" title="Delivery Interval">
                <?php foreach ($intervals as $interval): ?>
                    <option value="<?php echo $interval ?>" <?php if ($interval ==
                    $subscription->getInterval()): ?>selected="selected"<?php endif; ?>><?php echo $interval ?></option>
                <?php endforeach; ?>
            </select>
        </p>
    </form>
</div>
<script type="text/javascript">
    //<![CDATA[
    jQuery(function () {
        jQuery("#delivery_date_<?php echo $subscription->getId() ?>").datepicker({
            minDate: 2,
            showOn: "button",
            buttonImage: "<?php echo $this->getSkinUrl('images/autoship/calendar_icon.png')?>",
            buttonImageOnly: true,
            buttonText: "Click to change date.",
            dateFormat: "mm/dd/y",
            onSelect: function () {
                var form = jQuery(this).closest("form");
                updateMySubscriptionPost(form);
            }
        })
    });
    //]]>
</script>