<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Add Slideshow')?></h3></td>
            <td class="a-right">
            	<?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="add_form" name="add_form" method="post" action="<?php echo $this->getUrl('*/*/save')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Enter the page information below')?></h4>
        <fieldset id="my-fieldset" class="fieldset-wide">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Name')?> <span class="required">*</span></td>
                    <td class="value"><input class="input-text required-entry" name="addform[name]" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Status')?> <span class="required">*</span></td>
                    <td class="value">
                    	<select name="addform[status]">
                    		<?php $statuses = Mage::helper('pagemanager')->getStatuses(); ?>
                    		<?php foreach($statuses as $key => $title): ?>
	                    		<option value="<?php echo $key?>"><?php echo $this->__($title)?></option>
                    		<?php endforeach; ?>
                    	</select>
                    </td>
                </tr>    
                <tr>
                    <td class="label"><?php echo $this->__('Position')?></td>
                    <td class="value"><input class="input-text" name="addform[position]" style="width:30px;" /></td>
                </tr>
                <?php if(Mage::getStoreConfig("pagemanager/settings/show_quickview_setting", 0) == 1) { ?>
                <tr>
                    <td class="label"><?=$this->__('Use QuickView')?></td>
                    <td class="value">
                        <select name="addform[quickview_enabled]">
                            <option value="1"><?php echo $this->__("Yes") ?></option>
                            <option value="0"><?php echo $this->__("No") ?></option>
                        </select>
                    </td>
                </tr>
                <?php } ?>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var addForm = new varienForm('add_form');
</script>
