<?php
/**
 * @author    Mediotype Developement <diveinto@mediotype.com>
 * @copyright 2019 Mediotype. All rights reserved.
 */
/** @var $this \Mage_Catalog_Block_Product_View */
?>
<?php
/** @var \Hylete_Pixlee_Helper_Data $helper */
$helper = Mage::helper('hylete_pixlee');
$product = $this->getProduct();
if ($product !== null && $helper->isActive()): ?>
    <div id="pixlee_container"></div>
    <script type="text/javascript">
        window.PixleeAsyncInit = function () {
            Pixlee.init({
                apiKey: '<?php echo $helper->getAccountApiKey() ?>'
            });
            Pixlee.addCategoryWidget({
                accountId: <?php echo $helper->getAccountId() ? $helper->getAccountId() : "''" ?>,
                widgetId: <?php echo $helper->getProductWidgetId() ? $helper->getProductWidgetId() : "''" ?>,
                categoryName: '<?php echo $this->escapeHtml($product->getName()) ?>',
                fallbackAlbumId: <?php echo $helper->getAlbumIdByProductId($product->getId()) ? $helper->getAlbumIdByProductId($product->getId()) : "''" ?>,
                fallbackThreshold: 2
            });
        };
    </script>
    <script src="//assets.pixlee.com/assets/pixlee_widget_1_0_0.js"></script>
<?php endif ?>
