<?php
/**
 * Copyright (c) 2009-2016 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Hylete
 * @copyright   Copyright (c) 2009-2016 Vaimo AB
 */

// TODO: Refactor to not call model in template

$_shiptoCms = Mage::getModel('cms/block')->load('header_ship_to');
?>

<header id="header">
    <div class="logo">
        <div class="logo-desktop hidden-inline-block-xs hidden-inline-block-sm">
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>">
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
            </a>
        </div>
        <div class="visible-inline-block-xs visible-inline-block-sm logo-mobile">
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>">
                <span class="sprite-logo"></span>
            </a>
        </div>
    </div>

    <div class="container">
        <div class="left">
            <a class="hidden-inline-block-xs hidden-inline-block-sm" data-togglelink="header-newsletter" data-togglegroup="header" data-toggleaction="click mouseenter mouseleave" data-toggleautoclose="true"><?php echo $this->__('newsletter');?> <span class="fa fa-angle-down"></span></a>
            <a class="hidden-inline-block-xs hidden-inline-block-sm" data-togglelink="header-follow" data-togglegroup="header" data-toggleaction="click mouseenter mouseleave" data-toggleautoclose="true"><?php echo $this->__('follow us');?> <span class="fa fa-angle-down"></span></a>
            <a class="hidden-inline-block-xs hidden-inline-block-sm" data-togglelink="header-support" data-togglegroup="header" data-toggleaction="click mouseenter mouseleave" data-toggleautoclose="true"><?php echo $this->__('support');?> <span class="fa fa-angle-down"></span></a>
            <a class="visible-inline-block-xs visible-inline-block-sm mobile-nav" id="toggle-nav"><span class="sprite-mobile-menu"></span></a>
            <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                <a class="mobile-search visible-inline-block-xs visible-inline-block-sm">
                    <span class="sprite-search-white"></span>
                </a>
            <?php endif; ?>
        </div>

        <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <div class="mobile-search-wrapper">
                <div class="mobile-search-section">
                    <div class="container">
                        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalogsearch/form.mini.phtml')->toHtml() ?>
                    </div>
                </div>
                <div class="quick-link-wrapper">
                    <div class="container">
                        <?php echo $this->getLayout()->createBlock('cms/block', 'quick-links')->setBlockId('quick_links')->toHtml() ?>
                    </div>
                </div>
           </div>
        <?php endif; ?>

        <div class="right">
            <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                <div class="hidden-inline-block-xs hidden-inline-block-sm menu-search">
                    <div class="search-wrapper">
                        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalogsearch/form.mini.phtml')->toHtml() ?>
                        <div class="quick-link-wrapper">
                            <?php echo $this->getLayout()->createBlock('cms/block', 'quick-links')->setBlockId('quick_links')->toHtml() ?>
                        </div>
                    </div>
                    <a class="search-button">
                        <span class="sprite-search-white"></span>
                        <span><?php echo $this->__('search')?></span>
                    </a>
                </div>
            <?php endif; ?>

            <?php if ($_shiptoCms->getIsActive()):?>
                <a class="hidden-inline-block-xs hidden-inline-block-sm header-shipto" data-togglelink="header-shipto" data-togglegroup="header" data-toggleaction="click mouseenter mouseleave" data-toggleautoclose="true"><?php echo $this->__('ship to');?>: <span class="code"><?php echo Mage::app()->getStore()->getCode();?></span> <span class="fa fa-angle-down"></span></a>
            <?php endif;?>
            <?php echo $this->getChildHtml('header.welcome'); ?>
            <?php echo $this->getChildHtml('headerCart'); ?>
        </div>
    </div>

    <div data-togglecontent="header-newsletter" data-togglegroup="header" data-toggleaction="mouseleave" data-toggleautoclose="true">
        <div class="container"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->setFormId('header')->toHtml() ?></div>
    </div>

    <div data-togglecontent="header-follow" data-togglegroup="header" data-toggleaction="mouseleave" data-toggleautoclose="true">
        <div class="container follow-us">
            <a href="http://instagram.com/trainhylete" target="_blank"><span class="fa fa-instagram"></span></a>
            <a href="https://twitter.com/#!/trainHYLETE" target="_blank"><span class="fa fa-twitter"></span></a>
            <a href="http://www.facebook.com/hylete" target="_blank"><span class="fa fa-facebook"></span></a>
            <a href="http://www.youtube.com/trainHYLETE" target="_blank"><span class="fa fa-youtube"></span></a>
            <a href="http://pinterest.com/explore/trainhylete" target="_blank"><span class="fa fa-pinterest"></span></a>
        </div>
    </div>

    <div data-togglecontent="header-support" data-togglegroup="header" data-toggleaction="mouseleave" data-toggleautoclose="true">
        <div class="container">
            <?php echo $this->getLayout()->createBlock('cms/block', 'footer-info')->setBlockId('footer_info')->toHtml() ?>
        </div>
    </div>

    <?php if ($_shiptoCms->getIsActive()):?>
        <div data-togglecontent="header-shipto" data-togglegroup="header" data-toggleaction="mouseleave" data-toggleautoclose="true">
            <div class="container shipto">
                <?php echo $_shiptoCms->getContent();?>
            </div>
        </div>
    <?php endif;?>
</header>

<?php echo $this->getChildHtml('topMenu') ?>