<?php

/**
 * Apple Pay patch express catalog setup template.
 * @category  Template
 * @package   Mediotype_ApplePayPatch
 * @author    Rick Buczynski <rick@mediotype.com>
 * @copyright 2018 Mediotype
 */

?>
<?php if ($this->isEnabled() && $this->isEnabledPdp()) : ?>
<?php $_price = $this->getProduct()->getFinalPrice(); ?>
<?php if ($this->getProduct() && $this->getProduct()->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_GROUPED) : ?>
<?php $_price = 1; ?>
<?php endif; ?>
<script type="text/javascript">
    if (typeof Translator !== 'object' && typeof Translate == 'object') {
        var Translator = new Translate([]);
    }

    if (typeof Translator === 'object') {
        Translator.add({
            'We were unable to complete the request. Please try again.':
                '<?php echo $this->__('We were unable to complete the request. Please try again.'); ?>'
        })
    }

    document.observe('dom:loaded', function() {
        var express = new BraintreeApplePayExpress(
            '<?php echo $this->getToken(); ?>',
            '<?php echo Mage::app()->getStore()->getFrontendName(); ?>',
            '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
            'product',
            {
                clientTokenUrl  : '<?php echo $this->getUrl('applepay/index/clientToken'); ?>',
                submitUrl       : '<?php echo $this->getUrl('applepay/index/submit') ?>',
                fetchMethodsUrl : '<?php echo $this->getUrl('applepay/index/fetchShippingMethods'); ?>',
                successUrl      : '<?php echo $this->getUrl('checkout/onepage/success'); ?>'
            },
            {
                productId   : <?php echo (int) $this->getProduct()->getId(); ?>,
                virtual     : <?php echo $this->getProduct()->isVirtual() ? 'true' : 'false'; ?>
            }
        );

        express.setAmount('<?php echo $this->helper('core')->currency($_price, false, false); ?>');

        if (typeof window.bundle !== 'undefined') {
            $(document).observe('bundle:reload-price', function (event) {
                if (typeof event.memo.priceInclTax !== 'undefined') {
                    express.setAmount(parseFloat(event.memo.priceInclTax).toFixed(2));
                }
            });
        }

        express.attachToButtons($$('[data-applepay]'));
    });
</script>
<?php endif; ?>
