<?php if ($this->isKlaviyoEnabled()): ?>
  <script text="text/javascript">
    var _learnq = _learnq || [];
   
    _learnq.push(['account', '<?php echo $this->getKlaviyoAccountId(); ?>']);

    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
      <?php $_customer = $this->getCustomer(); ?>
      _learnq.push(['identify', {
          $email: "<?php echo $_customer->getEmail(); ?>",
          $first_name: "<?php echo $_customer->getFirstname(); ?>",
          $last_name: "<?php echo $_customer->getLastname(); ?>"
      }]);
    <?php endif; ?>

    (function () { var b = document.createElement('script'); b.type = 'text/javascript'; b.async = true; b.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'a.klaviyo.com/media/js/analytics/analytics.js'; var a = document.getElementsByTagName('script')[0]; a.parentNode.insertBefore(b, a); })();
  </script>
<?php endif; ?>