<?php
/**
 * Sweet Tooth
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Sweet Tooth SWEET TOOTH POINTS AND REWARDS
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth License is available at this URL:
 *     https://www.sweettoothrewards.com/terms-of-service
 * The Open Software License is available at this URL:
 *      http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * By adding to, editing, or in any way modifying this code, Sweet Tooth is
 * not held liable for any inconsistencies or abnormalities in the
 * behaviour of this code.
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by Sweet Tooth, outlined in the
 * provided Sweet Tooth License.
 * Upon discovery of modified code in the process of support, the Licensee
 * is still held accountable for any and all billable time Sweet Tooth spent
 * during the support process.
 * Sweet Tooth does not guarantee compatibility with any other framework extension.
 * Sweet Tooth is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to
 * support@sweettoothrewards.com or call 1.855.699.9322, so we can send you a copy
 * immediately.
 *
 * @category   [TBT]
 * @package    [TBT_Rewards]
 * @copyright  Copyright (c) 2014 Sweet Tooth Inc. (http://www.sweettoothrewards.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/**
 * Admin Order Create Customer Balance
 *
 * @category   TBT
 * @package    TBT_Rewards
 * @author     Sweet Tooth Inc. <support@sweettoothrewards.com>
 */
?>
<div id="rewards-order-create-customer-balance-area" style="display:none;">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="fieldset-legend head-catalog-product icon-head">Customer Rewards Balance</h4>
        </div>
        <div class="fieldset">
          <table style="width:100%;">
            <tr>
                <td><?php echo $this->__("Usable Points Balance");?>: <span class="bold"><?php echo $this->getCustomerUsablePointsString();?></span></td>
            </tr>
          </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    var orderItemsObj = $('order-items');
    
    if (typeof orderItemsObj !== 'undefined') {
        var orderItemsTdObj = orderItemsObj.up('td');

        if (typeof orderItemsTdObj !== 'undefined') {
            orderItemsTdObj.insert({top: $('rewards-order-create-customer-balance-area')});
            $('rewards-order-create-customer-balance-area').show();
        }
    }
</script>