<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SubscribePro
 * @package   SubscribePro_Autoship
 * @author    Subscribe Pro Support <support@subscribepro.com>
 * @copyright 2009-2020 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php $_code = $this->getMethodCode() ?>
<?php /** @var SubscribePro\Service\PaymentProfile\PaymentProfileInterface $_paymentProfile */
    $_paymentProfile = $this->getMethod()->getSavedPaymentProfile() ?>
<?php echo $this->getChildHtml() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <input type="hidden" id="<?php echo $_code ?>_payment_token" name="payment[payment_token]"
           title="<?php echo $this->__('Payment Token') ?>" value="<?php echo $_paymentProfile->getPaymentToken() ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_payment_profile_id" name="payment[payment_profile_id]"
           title="<?php echo $this->__('Payment Profile ID') ?>" value="<?php echo $_paymentProfile->getId() ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_payment_profile_name" name="payment[payment_profile_name]"
           title="<?php echo $this->__('Payment Profile Name') ?>" value="<?php echo $_paymentProfile->getCustomerFacingName() ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_bank_routing_number" name="payment[bank_routing_number]"
           title="<?php echo $this->__('Bank Routing Number') ?>" value="<?php echo $_paymentProfile->getBankRoutingNumber() ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_bank_account_last_digits" name="payment[bank_account_last_digits]"
           title="<?php echo $this->__('Bank Account Last Digits') ?>" value="<?php echo $_paymentProfile->getBankAccountLastDigits() ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_is_new_echeck" name="payment[is_new_echeck]"
           title="<?php echo $this->__('Is New eCheck') ?>" value="0"/>
</ul>
