<?php
/**
 * Copyright (c) 2009-2017 Vaimo Group
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Cms
 * @copyright   Copyright (c) 2009-2017 Vaimo Group
 */
?>
<div class="vcms-structure-item-content-template" style="display: none">
    <div class="vcms-actions">
        <button class="vcms-structure-widget-configure" title="Configure" type="button"></button><button class="vcms-structure-widget-remove" title="<?php echo __('Remove'); ?>" type="button"></button>
    </div>
    <div class="js-vcms-preview-area vcms-preview-area"></div>
    <div class="vcms-preview-area-overlay"></div>
    <div class="js-vcms-new-widget-placeholder">
        <div class="vcms-placeholder-info">
            <div class="js-vcms-widget-name"></div>
            <div class="js-vcms-widget-description"></div>
        </div>
    </div>
</div>