<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SubscribePro
 * @package   SubscribePro_Autoship
 * @author    Subscribe Pro Support <support@subscribepro.com>
 * @copyright 2009-2020 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<script type="application/javascript">
    jQuery(document).ready(function() {
        // Config
        const subscribeProApplePayConfig = {
            isCustomerLoggedIn: <?php echo $this->isCustomerLoggedIn() ? 'true' : 'false' ?>,
            cartHasProductsToCreateNewSubscriptions: <?php echo $this->hasProductsToCreateNewSubscription() ? 'true' : 'false' ?>,
            onshippingcontactselectedUrl: '<?php echo $this->getUrl('autoship/applepay/onshippingcontactselected') ?>',
            onshippingmethodselectedUrl: '<?php echo $this->getUrl('autoship/applepay/onshippingmethodselected') ?>',
            onpaymentauthorizedUrl: '<?php echo $this->getUrl('autoship/applepay/onpaymentauthorized') ?>',
            createSessionUrl: '<?php echo $this->getCreateSessionUrl() ?>',
            apiAccessToken: '<?php echo $this->getApiAccessToken() ?>',
            paymentRequest: <?php echo json_encode($this->getApplePayPaymentRequest(), JSON_PRETTY_PRINT) ?>
        };
        // Init
        subscribeProApplePay.init(subscribeProApplePayConfig);
    });
</script>