<?php if ($this->isButtonEnabled('refer_friends')): ?>
    <div id="sweettooth-refer-friends" style="visibility: hidden;" data-st-referral>
        <div class="rewards-modal block">
            <div class="head block-title">
                <strong style="display: inline-block;"><?php echo $this->__("Share your referral link!") ?></strong>
                <a href="javascript://" title="Close" class="btn-remove" style="margin-top: 3px;"><?php echo $this->__("Close"); ?></a>
            </div>
            <div class="content block-content">
                <div class="modal-step">
                    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
                        <?php echo $this->getModalHtml(); ?>
                    <?php else : ?>
                        <?php echo $this->getLoginMessage(); ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div id="rewards_modal_mask" class="rewards-modal-mask"></div>
    </div>

    <script type="text/javascript">
        (function() {
            Event.observe(document, 'dom:loaded', function() {
                var modalCloseButton = $$('#sweettooth-refer-friends .head .btn-remove')[0];
                var modalMask = $('rewards_modal_mask');
                var modal = $('sweettooth-refer-friends');

                var closeModal = function() {
                    modal.setStyle({visibility: 'hidden'});
                };

                Event.observe(window, 'keydown', function(e) {
                    if (!e) { var e = window.event; }

                    // Escape key is pressed
                    if (e.keyCode == 27) {
                        closeModal();
                    }
                });

                Event.observe(modalCloseButton, 'click', function() {
                    closeModal();
                });

                Event.observe(modalMask, 'click', function() {
                    closeModal();
                });
            });
        })();
    </script>
<?php endif; ?>
