<div id="facebook-like-modal" class="facebook-like-modal hidden">
    <div class="fb-header">
        <span>Facebook Like</span>
    </div>
    <div class="fb-wrapper">
        <div class="fb-content">
            <div class="button-row html5">
                <div  class="fb-like"
                      data-href="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>"
                      data-layout="standard"
                      data-action="like"
                      data-show-faces="false"
                      data-share="false">
                </div>
            </div>
        </div>
        <div class="fb-footer">
            <button onclick="$('facebook-like-modal').addClassName('hidden'); ">Close</button>
        </div>
    </div>
</div>