<?php
/**
 * Copyright (c) 2009-2016 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Hylete
 * @copyright   Copyright (c) 2009-2016 Vaimo AB
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>

<?php
/** @var Vaimo_Hylete_Helper_Checkout $checkoutHelper */
$checkoutHelper = $this->helper('hylete/checkout');
$spProducts = Mage::helper('autoship/quote')->hasProductsToCreateNewSubscription();

/** @var Mage_Customer_Model_Session $_customerSession */
$_customerSession = Mage::getSingleton('customer/session');

$_customerGroupId = $_customerSession->getCustomerGroupId();

/** @var Mediotype_HyletePrice_Helper_Data $_hyletePriceHelper */
$_hyletePriceHelper = $this->helper("mediotype_hyleteprice");


?>

<div class="cart">
    <div class="mobile-cart-header visible-xs">
        <?php if(!$this->hasError()): ?>
            <ul class="checkout-types">
                <div class="cart-above-checkout-button">
                    <?php echo $this->getChildHtml('cart-above-checkout-button')?>
                </div>
                <?php foreach ($this->getMethods('methods') as $method): ?>
                    <?php $methodHtml = $this->getMethodHtml($method) ?>
                    <?php if ($methodHtml != '' && $method !== 'checkout.cart.methods.multishipping') : ?>
                        <li><?php echo $methodHtml; ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <?php if (!$_customerSession->isLoggedIn()) : ?>
            <div class="cart-login">
                <span class="cart-login-msg"><?php echo $this->getLayout()->createBlock('cms/block', 'mobile_cart_login')->setBlockId('mobile_cart_login')->toHtml() ?></span>
            </div>
        <?php endif; ?>
    </div>
    <div class="row">
        <div class="col-md-12 page-title title-buttons">
            <h1 class="cart-title"><?php echo $this->__('cart') ?></h1>
        </div>
    </div>
    <div class="row">
        <?php if($this->getContinueShoppingUrl()): ?>
            <a href="<?php echo $this->getContinueShoppingUrl();?>" class="continue-shopping">
                <i class="far fa-angle-double-left"></i>
                <?php echo $this->__('continue shopping') ?>
            </a>
        <?php endif; ?>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            <?php echo $this->getChildHtml('form_before') ?>
            <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
                <?php echo $this->getBlockHtml('formkey'); ?>
                <fieldset>
                    <table id="shopping-cart-table" class="data-table cart-table">
                        <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                        <thead>
                        <tr>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-center">&nbsp;</th>
                            <th rowspan="<?php echo $mergedCells; ?>" class="hidden-xs">&nbsp;</th>
                            <th rowspan="<?php echo $mergedCells; ?>" class="th-title"><span class="nobr"><?php echo $this->__('product') ?></span></th>
                            <th class="a-center hidden-xs" colspan="<?php echo $mergedCells; ?>">
                                    <span class="nobr">
                                        <?php echo $this->__('retail value'); ?>
                                    </span>
                            </th>
                            <th class="a-center hidden-xs" colspan="<?php echo $mergedCells; ?>">
                                    <span class="nobr">
                                        <?php echo $this->__($_hyletePriceHelper->getPriceLabelByCustomerGroup()); ?>
                                    </span>
                            </th>
                            <th rowspan="<?php echo $mergedCells; ?>" width="100" class="a-center"><?php echo $this->__('qty') ?></th>
                            <th class="a-center hidden-xs" colspan="<?php echo $mergedCells; ?>">
                                <?php echo $this->__('subtotal') ?>
                            </th>
                        </tr>
                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                            <tr>
                                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                            </tr>
                        <?php endif; ?>
                        </thead>
                        <tbody>
                        <?php foreach($this->getItems() as $_item): ?>
                            <?php echo $this->getItemHtml($_item) ?>
                        <?php endforeach ?>
                        </tbody>

                    </table>
                    <script type="text/javascript">decorateTable('shopping-cart-table')</script>
                </fieldset>

                <p class="actions">
                    <button type="submit"
                            name="update_cart_action"
                            value="empty_cart"
                            title="<?php echo Mage::helper('core')->quoteEscape($this->__('Clear Cart')); ?>"
                            class="button-text"
                            id="empty_cart_button"
                            data-confirm-msg="<?php echo $this->__('Are You Sure?'); ?>">
                        <i class="far fa-angle-double-left"></i><span> <?php echo $this->__('clear cart') ?></span>
                    </button>
                </p>
            </form>

            <div class="cart-collaterals">
                <?php if ($_crosssell = $this->getChildHtml('crosssell')): ?>
                    <div class="crosssell">
                        <?php echo $_crosssell ?>
                    </div>
                <?php endif; ?>
                <?php
                $websiteCode = Mage::app()->getWebsite()->getCode();
                $websiteCheck = ($websiteCode == 'base' || $websiteCode == 'uk');
                ?>
                <?php if (Mage::getSingleton('customer/session')->isLoggedIn()):?>
                    <?php if (!$spProducts) : ?>
                        <script type="text/javascript">
                            var $j = jQuery.noConflict();
                            $j(document).ready(function() {
                                var slider = $j('.rewards-box-spend-minicart');
                                $j('.rewards-box-spend-minicart').remove();
                                $j('.coupons-wrapper-logged').html(slider);
                            });
                        </script>

                        <div class="discounts">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 coupons-wrapper-logged">

                                </div>
                                <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 coupons-checkboxes">
                                    <?php echo $this->getChildHtml('coupon') ?>
                                    <div class="promo clearfix giftcard-wrapper">
                                        <!-- Display Only For Specific Store Views -->
                                        <?php
                                        if($_customerGroupId==0 OR $_customerGroupId==1)
                                        {
                                            echo $this->getChildHtml('checkout.cart.extra');
                                        }
                                        ?>
                                    </div>
                                    <div class="promo clearfix giftcard-wrapper">
                                        <input type="checkbox" id="open-giftcard" class="open-giftcard stay-checked"/>
                                        <label for="open-giftcard"><?php echo $this->__('Pay with a gift card') ?> </label>
                                        <div class="discount-giftcard giftcard-content">
                                            <?php echo $this->getChildHtml('giftcards') //For Enterprise ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endif;?>
                <?php else: ?>
                    <?php if( !$spProducts ) : ?>
                    <div class="discounts">
                        <div class="row">
                            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 coupons-wrapper">
                                <?php echo $this->getChildHtml('coupon') ?>
                                <div class="promo clearfix govx-wrapper">
                                    <input type="checkbox" id="open-govx" class="open-promo"/>
                                    <label for="open-govx"><?php echo $this->__('Military & First Responder Discount') ?> </label>
                                    <div class="govx-button-cart-page" style="display:none;">
                                        <script src="https://auth.govx.com/public/govx-popup-registration.js"></script>
                                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('govx-cart-auth-link')->toHtml(); ?>
                                        <script>
                                            jQuery(document).on('click', '.govx-popup-registration-link', function(e) {
                                                e && e.preventDefault();
                                                window.govx.showGovXTickets(this.href);
                                            });
                                            jQuery("#open-govx").change(function() {
                                                if(this.checked) {
                                                    jQuery('.govx-button-cart-page').show();
                                                }else{
                                                    jQuery('.govx-button-cart-page').hide();
                                                }
                                            });
                                        </script>
                                    </div>
                                </div>
                                <div class="promo giftcard-wrapper">
                                    <!-- Display Only For Specific Store Views -->
                                    <?php
                                    if($_customerGroupId==0 OR $_customerGroupId==1)
                                    {
                                        echo $this->getChildHtml('checkout.cart.extra');
                                    }
                                    ?>
                                </div>
                            </div>
                            <?php $_ajaxLoginHelper = Mage::helper('mediotyoe_ajaxlogin'); ?>
                            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                                <div class="cart-login" id="firecheckout-form">
                                    <div class="login-section-actions">
                                        <div class="login-section-action">
                                            <?php if ($_ajaxLoginHelper->isEnabled()): ?>
                                                <a onclick="AjaxLogin.openLogin();" class="button button-login login-section-button">
                                                    <span class="fal fa-user"></span>
                                                    <?php echo $this->__('Log in') ?>
                                                </a>
                                                <div>
                                                    <p>or</p>
                                                    <a onclick="AjaxLogin.openRegistration();" class="button-create-account"><?php echo $this->__('create an account')?></a>
                                                </div>
                                            <?php else: ?>
                                                <a href="<?php echo $this->getUrl('customer/account/login') ?>" class="button button-login login-section-button firecheckout-login">
                                                    <span class="fal fa-user"></span>
                                                    <?php echo $this->__('Log in') ?>
                                                </a>
                                                <div>
                                                    <p>or</p>
                                                    <a href="<?php echo $this->getUrl('customer/account/create') ?>" class="button-create-account"><?php echo $this->__('create an account')?></a>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <?php if (Mage::getStoreConfig('sociallogin/facebook/activate')):?>
                                            <div class="login-section-action">
                                                <a onclick="return facebookPopup();" class="button button-login-facebook login-section-button">
                                                    <i class="fab fa-facebook-f"></i><?php echo $this->__('FACEBOOK LOGIN');?>
                                                </a>
                                            </div>
                                        <?php endif;?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>

                <?php endif; ?>

                <script type="text/javascript">
                    var forgotpasswordUrl = '<?php echo $this->getUrl('firecheckout/index/forgotpassword', array('_secure'=>$this->getRequest()->isSecure())) ?>';

                            var loginLinks = [
                                '.firecheckout-login',
                                'a[href="<?php echo Mage::helper('customer')->getLoginUrl() ?>"]'
                            ];

                            document.observe("dom:loaded", function() {
                                firecheckoutWindow = new FC.Window({
                                    triggers: {
                                        login: {
                                            el    : $$(loginLinks.join(', ')),
                                            event : 'click',
                                            window: $('firecheckout-login-window')
                                        },
                                        forgot: {
                                            el    : $$('.firecheckout-forgot'),
                                            event : 'click',
                                            window: $('firecheckout-forgot-window')
                                        }
                                    }
                                });
                            });
                        </script>


                        <?php echo $this->getChildHtml('checkout_cart_widget') //For Enterprise ?>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 totals">
                    <?php echo $this->getChildHtml('totals'); ?>
                    <?php if(!$this->hasError()): ?>
                        <div class="cart-above-checkout-button">
                            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart-above-checkout-button')->toHtml(); ?>
                        </div>


                        <ul class="checkout-types">
                            <?php foreach ($this->getMethods('methods') as $method): ?>
                                <?php $methodHtml = $this->getMethodHtml($method) ?>
                                <?php if ($methodHtml != '' && $method !== 'checkout.cart.methods.multishipping') : ?>
                                    <li><?php echo $methodHtml; ?></li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                        <div class="cart-below-checkout-button">
                            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart-below-checkout-button')->toHtml(); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
