<?php
$summaryHelper = Mage::helper('rewards/sales_discount_summary');
$hasRewardsDiscounts = $summaryHelper->hasRewardsDiscountMap($this->getSource());
$otherDiscountAmount = $summaryHelper->getOtherDiscountAmount($this->getSource());
?>

<?php if ($hasRewardsDiscounts) : ?>
    <?php foreach ($summaryHelper->getRewardsDiscountMap($this->getSource()) as $rewardsDiscountRow) : ?>
    <tr class="rewards-cart-discounts-summary" style="display: none;">
        <td class="a-right"><?php echo $this->__("Rewards") . ': ' . $rewardsDiscountRow['label'];?></td>
        <td class="a-right" style="">
            <span class="price">
            <?php echo $summaryHelper->getQuoteCurrencyPrice($rewardsDiscountRow['discount_amount'] * (-1));?>
            </span>
        </td>
    </tr>
    <?php endforeach; ?>

    <?php if ($otherDiscountAmount > 0) : ?>
    <tr class="rewards-cart-discounts-summary" style="display: none;">
        <td class="a-right"><?php echo $this->__("Other");?></td>
        <td class="a-right" style="">
            <span class="price">
            <?php echo $summaryHelper->getQuoteCurrencyPrice($otherDiscountAmount * (-1));?>
            </span>
        </td>
    </tr>
    <?php endif; ?>

    <tr class="rewards-cart-discounts-summary" style="display: none;">
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
<?php endif; ?>

<?php
$totalLabel = $summaryHelper
    ->getTotalLabel($this->getTotal($this->getCode()), $this->getSource());
?>

<?php if ((float) $otherDiscountAmount || $hasRewardsDiscounts) : ?>

<tr <?php if ($hasRewardsDiscounts) : ?>class="rewards-cart-discounts-summary-header summary-total" onclick="expandDetails(this, '.rewards-cart-discounts-summary')"<?php endif;?>>
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal($this->getCode())->getStyle() ?>" class="a-right">
        <div <?php if ($hasRewardsDiscounts) : ?>class="summary-collapse"<?php endif;?>>
            <?php echo $this->escapeHtml($totalLabel); ?>
        </div>
    </td>
    <td style="<?php echo $this->getTotal($this->getCode())->getStyle() ?>" class="a-right">
        <?php if ($this->getRenderingArea() == $this->getTotal($this->getCode())->getArea()): ?><strong><?php endif; ?>
            <span class="price">
            <?php echo $summaryHelper->getQuoteCurrencyPrice($this->getTotal($this->getCode())->getValue()); ?>
            </span>
        <?php if ($this->getRenderingArea() == $this->getTotal($this->getCode())->getArea()): ?></strong><?php endif; ?>
    </td>
</tr>

<?php endif; ?>