<script type="text/javascript">
    window.sweettooth = window.sweettooth || {};
    sweettooth.slider = sweettooth.slider || {};

    sweettooth.slider.afterAjax = function(response) {
        var result = response.responseJSON;
        
        if (result.hasOwnProperty('error') && result.error === true) {
            this.logMessage(result.message);
        } else {
            var fetchReviewUrl = '<?php echo $this->getUrl('rewards/firecheckout_redeem/review', array('_forced_secure' => $this->getRequest()->isSecure())) ?>';
            // PATCH elvin@VAIMO
            // use firecheckout "magic" method updateSections()
            checkout.updateSections(['payment-method', 'review']);
//            new Ajax.Request(fetchReviewUrl, {
//                onSuccess: function (t) {
//                    var html = t.responseText;
//                    html = html.replace('checkout-review-submit', 'st-checkout-review-submit');
//
//                    $('checkout-review-load').update(html);
//                    $('st-checkout-review-submit').remove();
//                }
//            });
            //~ PATCH
        }
    };
</script>