<?php
/**
 * Copyright (c) 2009-2011 Icommerce Nordic AB
 *
 * Icommerce reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Icommerce, except as provided by licence. A licence
 * under Icommerce's rights in the Program may be available directly from
 * Icommerce.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Icommerce
 * @package     Icommerce_AdminFeed
 * @copyright   Copyright (c) 2009-2011 Icommerce Nordic AB
 */
 ?>
<div class="content-header adminfeed notifications">
    <h2><?php echo $this->__('Messages Inbox')?></h2>
    <p><?php echo $this->__('In this view you can see all your messages from us. <br />By clicking on the subject line, you can expand / fold your message.')?></p>
</div>

<div class="entry-edit adminfeed notifications">
    
    <form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getFormAction(); ?>">
    	<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    	<div class="grid">
    		
    		<?php $notifications = $this->getNotifications(); ?>
    		<?php if(count($notifications) < 1): ?>
    			Empty
    		<?php else:?>
    		
    		<table cellspacing="0">
    			<thead>
    			<tr class="headings">
    				<th><?php echo $this->__('Severity') ?></th>
    				<th><?php echo $this->__('Date Added') ?></th>
    				<th><?php echo $this->__('Message') ?></th>
    				<th><?php echo $this->__('Actions') ?></th>
    			</tr>
    			</thead>
    			<tbody>
    				<?php foreach($notifications as $notification): $id = $notification['notification_id']; ?>
    					<tr class="<?php if(!$this->isRead($id)) echo 'unread';?>">
    					    <td class="a-center" width="20"><?php echo $this->getSeverity($notification['severity'])?></td>
    					    <td width="50"><?php echo $notification['date_added'] ?></td>
    					    <td>
    					    	<b><a href="#" onclick="Effect.toggle('message-details-<?php echo $id?>', 'appear', { duration: 0.5 }); return false;"><?php echo $notification['title']; ?></a></b>
    					    	<div id="message-details-<?php echo $id?>" style="display:none">
    					    		<?php echo $notification['description']; ?>
    					    	</div>
    					    </td>
    					    <td width="100">
    					    	<?php if($this->isRead($id)):?>
    					    		<a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/notifications/markasunread/",array("id"=>$id));?>">
    					    			<?php echo $this->__('Mark as Unread')?></a>
    					    	<?php else: ?>
    					    	<a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/notifications/markasread/",array("id"=>$id));?>">
    					    		<?php echo $this->__('Mark as Read')?></a>
    					    	<?php endif; ?>
    					    	<br />
    					    	<a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/notifications/delete/",array("id"=>$id));?>">
    					    		<?php echo $this->__('Delete')?></a>
    					    </td>	                 
    					</tr>
    				<?php endforeach;?>	
    					
    			</tbody>
    	   </table>
    	   <?php endif;?>
    	</div>
    </form>
    
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>

