<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SubscribePro
 * @package   SubscribePro_Autoship
 * @author    Subscribe Pro Support <support@subscribepro.com>
 * @copyright 2009-2020 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php
/** @var SubscribePro_Autoship_Helper_Hosted $hostedHelper */
$hostedHelper = Mage::helper('autoship/hosted');
?>
<?php if (Mage::getStoreConfig('payment/subscribe_pro/active') == '1'): ?>
    <script type="text/javascript">
        var iframeEnvironmentKey = "<?php echo $this->getEnvironmentKey() ?>";
    </script>
    <script src="<?php echo $hostedHelper->getIframeScriptUrl() ?>"></script>
    <script src="<?php echo $hostedHelper->getJqueryPaymentScriptUrl() ?>"></script>
    <script src="<?php echo $hostedHelper->getJqueryCcScriptUrl() ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/autoship/checkout.js') ?>"></script>
<?php endif; ?>
