<?php /** @var TBT_Rewards_Block_Product_View_Points_Earned $this */ ?>
<?php $tooltipHtml = $this->helper('hylete_rewards')->getRewardPointsTooltipHtml() ?>

<div class="distri_section js-tooltip-container">
    <?php foreach ($this->getDistriRewards() as $reward_currency => $reward_amount): ?>
        <?php $points_summary = $this->getPointsString($reward_amount, $reward_currency); ?>

        <div id="point_summary_points" style="display:none;"><?php echo $points_summary; ?></div>
        <div class="you_will_earn">
            <span>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('points_summary')->toHtml() ?>

            <?php if ($this->getShowEarningFrom()) : ?>
                <?php //echo $this->__('Earn <strong>%s</strong> + Free Shipping & Returns', $points_summary); ?>
            <?php else :?>
                <?php //echo $this->__('Earn <strong>%s</strong> + Free Shipping & Returns', $points_summary); ?>
            <?php endif; ?>
            </span>

            <?php if ($tooltipHtml): ?>
                <!-- Moved to CMS block "points_summary"
                <span class="points-info">
                    <span class="points-info__link js-tooltip-link" data-elevio-article="85107">
                        <span class="fal fa-question-circle"></span>
                    </span>
                </span> -->
            <?php endif ?>

        </div>

        <?php if ($tooltipHtml): ?>
            <div style="display:none;">
                <div id="points-info-data"><?php echo $tooltipHtml ?></div>
            </div>
        <?php endif ?>

        <?php /* $reward_currency is almost always '1' and $reward_amount is an integer amount of points to display. */ ?>
        <?php $img_url = $this->getPointsImgUrl($reward_amount, $reward_currency); ?>
        <?php $imgPath = Mage::getSingleton('rewards/currency')->load($reward_currency)->getImage(); ?>
        <?php if (!empty($imgPath)): ?>
            <img src="<?php echo $img_url; ?>" class="points_image points_currency_image-<?php echo $reward_currency ?>"/>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
