<?php
/**
 * Copyright (c) 2009-2017 Vaimo Group
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Cms
 * @copyright   Copyright (c) 2009-2017 Vaimo Group
 */
?>
<div class="vcms-toolbar">
    <div id="js-vcms-structure-button-group" class="vcms-button-group">
        <button type="button" id="js-vcms-save-structure">
            <img src="<?php echo $this->getSkinUrl('images/vaimo_cms/icon-save.gif') ?>" alt="" />
            <?php echo $this->__('Save Structure'); ?>
        </button>
        <button type="button" id="js-vcms-cancel-structure"><?php echo $this->__('Cancel') ?></button>
        <button type="button" id="js-vcms-add-cms-block"><?php echo $this->__('Add CMS Static Block') ?></button>
        <button type="button" id="js-vcms-add-widget"><?php echo $this->__('Add Widget') ?></button>
    </div>
    <div id="js-vcms-staging-button-group" class="vcms-button-group">
        <button type="button" id="js-vcms-publish-draft"><?php echo $this->__('Publish') ?></button>
        <button type="button" id="js-vcms-discard-draft"><?php echo $this->__('Discard') ?></button>
    </div>
    <a href="<?php echo $this->getDisableEditModeUrl() ?>" class="vcms-exit-edit-mode vcms-navigation-exclude"><?php echo $this->__('[X] Exit Edit & Preview Mode') ?></a>
</div>