<li>
    <label for="rewards_referral">
        <?php
        if ($this->showReferralEmail() && !$this->showReferralCode()) {
            echo $this->__('enter referrer\'s email');
        } elseif (!$this->showReferralEmail() && $this->showReferralCode()) {
            echo $this->__('Referral Code');
        } else {
            echo $this->__('Referral E-mail or Code');
        }
        ?></label>
    <input type="text" name="rewards_referral" id="rewards_referral" class="input-text" value="<?php echo $this->getCurrentAffiliate(); ?>"/>
</li>