
<?php

$userData = $this->getResponse();

?>
<script>
    grecaptcha.ready(function () {
        grecaptcha.execute('6LfKHLIUAAAAACn-USCuObJmm5F3cPJCxsHwdeSN', { action: 'registration' })
            .then(function (token) {
                var recaptchaResponse = document.getElementById('recaptchaRegistrationResponse');
                recaptchaResponse.value = token;
            });
    });
</script>


<form class="form create account form-create-account"
      action = "/govx-auth/index/create"
      method="post" id="mcs-form-register-service-league" enctype="multipart/form-data" autocomplete="off"
      novalidate="novalidate">
    <?php echo $this->getBlockHtml('formkey'); ?>

    <fieldset class="fieldset create info">
        <input type="hidden" value="" name="recaptcha_response" id="recaptchaRegistrationResponse">
        <input type="hidden" name="customer_group_id"
               value="<?php echo $this->getCustomerGroupId(); ?>"/>
        <input type="hidden" name="success_url" value="">
        <input type="hidden" name="error_url"
               value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>">
        <input name="form_key" type="hidden"
               value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>

        <h2 class="legend"><?php echo $this->__('Your Name') ?></h2>
        <ul>
            <div class="customer-name">
                <div class="field control name-firstname">
                    <label for="firstname" class="required">First Name            <span class="required">*</span></label>
                    <div class="input-box">
                        <input type="text" id="firstname" name="firstname" value="<?php echo $this->escapeHtml($userData['firstName']) ?>" title="First Name" maxlength="255" class="input-text required-entry">
                    </div>
                </div>
                <div class="field control name-lastname">
                    <label for="lastname" class="required">Last Name<span class="required">*</span></label>
                    <div class="input-box">
                        <input type="text" id="lastname" name="lastname" value="<?php  echo $this->escapeHtml($userData['lastName']) ?>" title="Last Name" maxlength="255" class="input-text required-entry">
                    </div>
                </div>
            </div>

            <li>
                <label for="gender">Gender</label>
                <div class="input-box gender">
                    <p><input type="radio" value="1" name="gender" title="Gender" id="gender[1]">
                        <label for="gender[1]">Male</label></p>
                    <p><input type="radio" value="2" name="gender" title="Gender" id="gender[2]">
                        <label for="gender[2]">Female</label></p>
                </div>
            </li>
        </ul>
        <h2 class="legend section"><?php echo $this->__('Account Info') ?></h2>
        <label for="email_address" class="required"><?php echo $this->__('Email Address') ?> <span
                    class="required">*</span></label>
        <input type="email" name="email" id="email_address"
               value="<?php echo $this->escapeHtml($userData['email']) ?>"
               title="<?php echo $this->__('Email Address') ?>"
               class="span4 input-text validate-email required-entry"/>

        <label for="password" class="required"><?php echo $this->__('Password'); ?> <span
                    class="required">*</span></label>
        <input type="password" id="password" name="password"
               class="input-text required-entry validate-password"/>

        <label for="confirmation" class="required"><?php echo $this->__('Confirm Password'); ?>
            <span
                    class="required">*</span></label>
        <input type="password" id="confirmation" name="confirmation"
               class="input-text required-entry validate-cpassword"/>
        <?php if ($this->isNewsletterEnabled()): ?>
            <input type="hidden" name="is_subscribed" value="1"/>
        <?php endif ?>
        <?php echo $this->getChildHtml('rewards_referral'); ?>

    </fieldset>
    <br>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="Create Account">
                <span><?php echo $this->__('Create Account') ?></span></button>
        </div>
    </div>
</form>
<div data-role="loader" class="loading-mask" id="mcs-custom-loader-service-league" style="display: none;">
    <div class="loader">
        <img src="<?php echo $this->getSkinUrl('images/mediotype/loader-1.gif') ?>" alt="Loading...">
    </div>
    <div>
        <p class="message"></p>
    </div>
</div>
<div class="mcs-register-form-notif">
</div>
<script type="text/javascript">
    var registrationForm = new VarienForm('mcs-form-register-service-league', true);
</script>
<script>
    jQuery("#mcs-form-register-service-league").submit(function(event){
        event.preventDefault(); //prevent default action
        jQuery("#mcs-custom-loader-service-league").show();
        var post_url = jQuery(this).attr("action"); //get form action url
        var request_method = jQuery(this).attr("method"); //get form GET/POST method
        var form_data = jQuery(this).serialize(); //Encode form elements for submission

        jQuery.ajax({
            url : post_url,
            type: request_method,
            data : form_data
        }).done(function(response){ //
            response = data = jQuery.parseJSON(response);
            jQuery("#mcs-custom-loader-service-league .loader").hide();
            jQuery("#mcs-custom-loader-service-league .message").html(response.message);
            jQuery("#mcs-custom-loader-service-league .message").css("padding","20px");
            jQuery("#mcs-custom-loader-service-league .message").css("position","fixed");
            jQuery("#mcs-custom-loader-service-league .message").css("color","white");
            jQuery("#mcs-custom-loader-service-league .message").css("top","50%");
            jQuery("#mcs-custom-loader-service-league .message").css("width","100%");
            jQuery("#mcs-custom-loader-service-league .message").css("background-color","green");

            window.opener.location.href = "/customer/account";
            window.setTimeout( closeWindow, 5000 ); // 5 seconds

        });
    });
    function closeWindow(){
        var daddy = window.self;
        daddy.opener = window.self;
        daddy.close();

    }
</script>