<?php
/**
 * @author    Mediotype Developement <diveinto@mediotype.com>
 * @copyright 2019 Mediotype. All rights reserved.
 */
/** @var $this \Mage_Catalog_Block_Category_View */
?>
<?php

/** @var $_category \Mage_Catalog_Model_Category */
if ($_category = $this->getCurrentCategory()) : ?>
    <?php $_description = $this->helper('catalog/output')->categoryAttribute($_category, $_category->getDescription(), 'description'); ?>
    <?php if ($_description): ?>
        <div class="row">
            <div class="col-xs-12">
                <?php echo $_description ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif ?>
