<?php
/**
 * @author    Mediotype Development <diveinto@mediotype.com>
 * @copyright 2019 Mediotype. All rights reserved.
 *
 * @var $this Mage_Catalog_Block_Category_View
 */
?>
<?php if ($this->IsRssCatalogEnable()): ?>
    <a href="<?php echo $this->getRssLink() ?>"
       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe to RSS Feed')) ?>"
       class="rss-feed"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
<?php endif ?>
