<?php
$region_specific_text = (Mage::app()->getStore()->getCurrentCurrencyCode() == 'AUD') ? 'fortnightly' : ((Mage::app()->getStore()->getCurrentCurrencyCode() == 'NZD') ? 'fortnightly' : 'bi-weekly');
?>
<div style="position: relative;;line-height: 1.4; margin-top:10px;" class="afterpay-installments">Or 4 installments of <strong><?php echo $this->__($this->getInstalmentAmount()) ?></strong> 
with <img src="<?php echo $this->getSkinUrl('frontend/base/default/afterpay/images/ap-logo-152x31.png') ?>" style="width: 76px;vertical-align: middle;display: inline;
"></img><a href="#afterpay-what-is-modal" class="afterpay-what-is-modal-trigger">   <i class="fal fa-question-circle"></i> </a>
</div>