<?php if (Icommerce_Default_Helper_Data::isModuleActive('Icommerce_QuickCheckout')): ?>
	<?php
		/**
         * QuickCheckout is active! Generate a password for the user.
         * We are using type="hidden" to avoid auto completion by the browser.
         **/
        $_password = $this->helper('paymentshared')->generatePassword();
	?>
	<li id="register-customer-password" class="hide">
        <input type="hidden" name="billing[customer_password]" value="<?php echo $_password ?>" id="billing:customer_password" class="required-entry validate-password input-text" />
	    <input type="hidden" name="billing[confirm_password]" value="<?php echo $_password ?>" id="billing:confirm_password" class="required-entry validate-password input-text" />
	</li>
<?php else: ?>
	<li id="register-customer-password">
		<div class="input-box">
			<label for="billing:customer_password">
				<?php echo $this->__('Password') ?> <span class="required">*</span>
			</label><br/>
            <input type="password" name="billing[customer_password]" id="billing:customer_password"
            	title="<?php echo $this->__('Password') ?>"
            	class="required-entry validate-password input-text" />
		</div>
		<div class="input-box">
            <label for="billing:confirm_password">
            	<?php echo $this->__('Confirm Password') ?> <span class="required">*</span>
           	</label><br/>
            <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>"
            	id="billing:confirm_password"
            	class="required-entry validate-password input-text" />
		</div>
	</li>
<?php endif; ?>