<?php $_isReviewDisabled = (bool)Mage::getStoreConfig('advanced/modules_disable_output/Mage_Review'); ?>
<div id="tab-container">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#description-tab" data-toggle="tab"><?php echo $this->__('Description') ?></a></li>
        <li><a href="#more-info-tab" data-toggle="tab"><?php echo $this->__('More Info') ?></a></li>
        <?php if ($_isReviewDisabled !== true): ?>
        <li><a href="#reviews-tab" data-toggle="tab"><?php echo $this->__('Reviews') ?></a></li>
        <?php endif; ?>
    </ul>
    <div class="tab-content">
        <div id="description-tab" class="tab-pane active" >
            <?php if ($_description = $this->getChildHtml('product.description')) :?>
                <?php echo $_description; endif;?>
        </div>
        <div id="more-info-tab" class="tab-pane">
            <?php echo $this->getChildHtml('product.attributes') ?>
        </div>
        <?php if ($_isReviewDisabled !== true): ?>
        <div id="reviews-tab" class="tab-pane">
            <?php echo $this->getChildHtml('product.info.reviews') ?>
        </div>
        <?php endif; ?>
    </div>
</div>
<script>
    // on load of the page: switch to the currently selected tab
    var hash = window.location.hash;
    jQuery('.nav-tabs a[href="' + hash + '"]').tab('show', false);
</script>