<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SubscribePro
 * @package   SubscribePro_Autoship
 * @author    Subscribe Pro Support <support@subscribepro.com>
 * @copyright 2009-2020 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php $paymentProfiles = $this->getPaymentProfiles(); ?>
<div class="page-title">
	<h1><?php echo $this->__("My Bank Accounts") ?></h1>
</div>

<fieldset>
	<div class="pager">
		<p class="amount">
			<?php echo count($paymentProfiles); ?> <?php echo $this->__("Item(s)") ?>
		</p>
	</div>
	<table class="data-table" id="cc-table">
		<thead>
			<tr class="first last">
                <th><?php echo $this->__("Bank Account") ?></th>
                <th><?php echo $this->__("Bank Routing Number") ?></th>
				<th><?php echo $this->__("Delete") ?></th>
			</tr>
		</thead>
		<tbody>
		<?php
		$i= 0;
		/** @var SubscribePro\Service\PaymentProfile\PaymentProfileInterface $profile */
		foreach($paymentProfiles as $profile) :
			?>
			<?php if($i % 2 == 0) { $row = 'even'; } else { $row='odd'; } ?>
			<tr class="<?php echo $row; ?>">
                <td>
                    <?php echo $profile->getCustomerFacingName() ?>
                </td>
                <td>
                    <?php echo $profile->getBankRoutingNumber() ?>
                </td>
				<td>
					<span><a href="#" class="link-reorder" onclick="confirmDelete(<?php echo $profile->getId() ?>)"> Delete</a></span>
				</td>
			</tr>
			<?php $i++; ?>
		<?php endforeach; ?>
		</tbody>
	</table>
	<div class="pager">
		<p class="amount">
			<?php echo count($paymentProfiles); ?> <?php echo $this->__("Item(s)") ?>
		</p>
	</div>
</fieldset>

<br/>

<div class="buttons-set form-buttons">
	<p class="back-link"><a href="<?php echo Mage::getUrl('customer/account/'); ?>"><small>&#171;</small> Back</a></p>
	<button type="submit" class="button" title="Save" onclick="window.location.href='<?php echo Mage::getUrl('autoship/mybankaccounts/new'); ?>customerid/<?php echo Mage::getSingleton('customer/session')->getCustomer()->getId() ?>'">
		<span><span>New Bank Account</span></span>
	</button>
</div>
<script type="text/javascript">
function confirmDelete(id)
{
    var x;
    var r=confirm("Are you sure you want to delete this bank account?");
    if (r==true)
    {
        window.location="<?php echo Mage::getUrl('autoship/mybankaccounts/delete'); ?>id/" + id;
    }
    else
    {
        return false;
    }
}
</script>





