<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Manage pages')?></h3></td>
            <td class="a-right">
            	<?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">

    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Here is a list of all saved pages')?></h4>

    <?php echo $this->getChildHtml('massupdate') ?>

    <form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/massUpdate')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <div class="grid">
            <table cellspacing="0">
                <thead>
                <tr class="headings">
                    <th class="a-center" style="width:70px;">&nbsp;</th>
                    <th><?php echo $this->__('ID') ?></th>
                    <th><?php echo $this->__('Name') ?></th>
                    <th><?php echo $this->__('Status') ?></th>
                    <th><?php echo $this->__('Position') ?></th>
                    <th><?php echo $this->__('Action') ?></th>
                </tr>
                </thead>
                <tbody>

                    <?php $i = 0; ?>

                    <?php $items = $this->getPages(); ?>

                    <?php if(count($items) < 1): ?>
                        <?php echo $this->getChildHtml('empty'); ?>
                    <?php else: ?>

                        <?php foreach($items as $item): ?>

                                <tr class="<?php echo ''.($i%2 == 0 ? 'even ' : '')?>">
                                    <td class="a-center" width="20"><input type="checkbox" name="edit_form[mass_update_id][]" class="mass_update_checkbox" value="<?php echo $item['id']?>" /></td>
                                    <td class="a-center" width="20"><?php echo $item['id']?></td>
                                    <td><?php echo $item['name'] ?></td>
                                    <td><?php echo $item['status'] == '1' ? $this->__("Active") : $this->__("Inactive"); ?></td>
                                    <td width="20"><input type="text" class="input-text" name="edit_form[position][<?php echo $item['id']?>]" value="<?php echo $item['position'] ?>"></td>
                                    <td width="60">
                                        <a href="<?php echo $this->getRowUrl($item['id']) ?>"><?php echo $this->__('Edit') ?></a>
                                        <a href="<?php echo $this->getUrl('*/*/copy', array('id' => $item['id'])) ?>"><?php echo $this->__('Copy') ?></a>
                                    </td>
                                </tr>

                        <?php $i++; ?>
                        <?php endforeach;?>

                    <?php endif; ?>

                </tbody>
           </table>
        </div>
        <input type="hidden" name="edit_form[mass_update_action]" id="mass_update_action" value="" />
    </form>

</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>
