<?php
/**
 * Copyright (c) 2009-2016 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Hylete
 * @copyright   Copyright (c) 2009-2016 Vaimo AB
 */
?>
<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Account_Redeem
 */
?>
<div class="page-title">
    <h1><?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card'); ?></h1>
</div>
<div class="giftcardaccount">
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form id="giftcard-form" action="<?php echo $this->getRedeemActionUrl() ?>" method="post"<?php if (!$this->canRedeem()): ?> onsubmit="giftCardAccountLookupBalance(); return false;"<?php endif; ?>>
        <div id="giftcard_balance_lookup"></div>
        <div class="giftcard_code_container">
            <label for="giftcard_code"><?php echo $this->__('Enter gift card code') ?></label>
            <span>
                <input class="required-entry input-text giftcard_code" id="giftcard_code" name="giftcard_code" value="<?php echo $this->getCurrentGiftcard(); ?>" />
            </span>
            <?php if ($this->canRedeem()): ?>
                <button class="button" onclick="giftcardForm.submit()" type="button" value="<?php echo Mage::helper('core')->quoteEscape($this->__('Redeem Gift Card')) ?>"><span><span><?php echo $this->__('Redeem Gift Card') ?></span></span></button>
            <?php endif; ?>
        </div>

        <div class="button-set">
            <button class="button check-gc-status" id="gca_balance_button" type="button" value="<?php echo Mage::helper('core')->quoteEscape($this->__('Check status and balance')) ?>"><span><span><?php echo $this->__('Check status and balance') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
    var giftcardForm = new VarienForm('giftcard-form');
    function giftCardAccountLookupBalance() {
        if (giftcardForm.validator && !giftcardForm.validator.validate()) {
            return false;
        }
        new Ajax.Updater('giftcard_balance_lookup', '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck', array('_secure' => true)) ?>', {
            onCreate: function() {
                $('gc-please-wait').show()
            },
            onComplete: function() {
                $('gc-please-wait').hide();
                if ($$('.col-main .messages')) {
                    $$('.col-main .messages').invoke('hide');
                }
            },
            parameters : {giftcard_code : $('giftcard_code').value}
        });
    }
    $('gca_balance_button').observe('click', giftCardAccountLookupBalance);
    //]]>
    </script>
</div>
