<div class="newsletter">
    <form id="email_signup1" class="klaviyo_bare_embed_Jas8EZ" action="//manage.kmail-lists.com/subscriptions/subscribe" data-ajax-submit="//manage.kmail-lists.com/ajax/subscriptions/subscribe" method="GET" target="_blank" novalidate="novalidate">
        <input type="hidden" name="g" value="Jas8EZ">
        <div class="klaviyo_field_group">
            <label for="k_id_email"><?php //echo $this->__('get the latest') ?></label>
            <span><input type="email" value="" name="email" class="input-text required-entry validate-email" id="k_id_email1"
                         placeholder="<?php echo $this->__('enter your email') ?>"/></span>
            <button type="submit" class="button klaviyo_submit_button" title="<?php echo $this->__('Join') ?>">
                <?php echo $this->__('Join') ?>
            </button>
        </div>
        <div class="klaviyo_messages">
            <div class="success_message" style="display:none;"><?php echo $this->__('thank you for subscribing to the HYLETE newsletter') ?></div>
            <div class="error_message" style="display:none;"></div>
        </div>
    </form>
    <form id="footer-phone-signup" class="" action="javascript:mobilePhoneOptIn(document.getElementById('radiance-footer-phone-optin').value);"  novalidate="novalidate">
        <div class="radiance_field_group klaviyo_field_group">
            <label for="radiance-footer-phone-optin"><?php //echo $this->__('get the latest') ?></label>
            <span><input type="tel" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" value="" name="phone" class="input-text required-entry validate-phoneLax" id="radiance-footer-phone-optin"
                     placeholder="<?php echo $this->__('Enter Your Mobile Number') ?>"/></span>
            <button type="submit" class="button klaviyo_submit_button" title="<?php echo $this->__('Join') ?>">
            <?php echo $this->__('Join') ?>
           </button>
        </div>
        <div class="radiance_messages klaviyo_messages">
            <div class="success_message" style="display:none;">
                <span><?php echo $this->__('Thanks for subscribing!') ?></span><br/>
                <span><?php echo $this->__('Check your phone for a confirmation message.') ?></span>
            </div>
        </div>
    </form>
    <p class="footer_newsletter_giveaway">Subscribers will be entered in our monthly <strong>$500 eGift Card</strong> Giveaway.</p>
    <p class="footer_newsletter_giveaway_sub">(Double your chances by signing up for email and text.)</p>
</div>
<script type="text/javascript">
    KlaviyoSubscribe.attachToForms('#email_signup1', {
        hide_form_on_success: false,
        extra_properties: {
            $source: 'Website Footer'
        }
    });
    //<![CDATA[
    var newsletterSubscriberFormemail_signup = new VarienForm('email_signup1');
    //]]>
</script>
<script type="text/javascript">
    //<![CDATA[
    var  phoneSubscribe_signup = new VarienForm('footer-phone-signup');
    //]]>



    function mobilePhoneOptIn(phoneOptin) {

        RadianceLabs.linkSMS({opt_in_location:"website_footer",command:"OptInDiscount",phone:phoneOptin});

        jQuery(".radiance_messages > .success_message").fadeIn(1000);

    }


</script>


