<div class="newsletter">
    <form id="email_signup1" class="klaviyo_bare_embed_Jas8EZ" action="//manage.kmail-lists.com/subscriptions/subscribe" data-ajax-submit="//manage.kmail-lists.com/ajax/subscriptions/subscribe" method="GET" target="_blank" novalidate="novalidate">
        <input type="hidden" name="g" value="Jas8EZ">
        <div class="klaviyo_field_group">
            <label for="k_id_email"><?php //echo $this->__('get the latest') ?></label>
            <span><input type="email" value="" name="email" class="input-text required-entry validate-email" id="k_id_email1"
                         placeholder="<?php echo $this->__('enter your email') ?>"/></span>
            <button type="submit" class="button klaviyo_submit_button" title="<?php echo $this->__('Join') ?>">
                <?php echo $this->__('Join') ?>
            </button>
        </div>
        <div class="klaviyo_messages">
            <div class="success_message" style="display:none;"><?php echo $this->__('thank you for subscribing to the HYLETE newsletter') ?></div>
            <div class="error_message" style="display:none;"></div>
        </div>
    </form>
</div>
<script type="text/javascript">
    KlaviyoSubscribe.attachToForms('#email_signup1', {
        hide_form_on_success: false,
        extra_properties: {
            $source: 'Website Footer'
        }
    });
    //<![CDATA[
        var newsletterSubscriberFormemail_signup = new VarienForm('email_signup1');
    //]]>
</script>
