<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SubscribePro
 * @package   SubscribePro_Autoship
 * @author    Subscribe Pro Support <support@subscribepro.com>
 * @copyright 2009-2020 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
/** @var SubscribePro_Autoship_Block_Payment_Form_CC $this */
?>
<?php $_code = $this->getMethodCode() ?>
<ul class="form-list subscribepro-cc-form" id="payment_form_<?php echo $_code ?>" style="display:none;">

    <input type="hidden" id="<?php echo $_code ?>_payment_token" name="payment[payment_token]" title="<?php echo $this->__('Payment Token') ?>" value="<?php echo $this->getAdditionalInfo('payment_token') ?>" />
    <input type="hidden" id="<?php echo $_code ?>_is_new_card" name="payment[is_new_card]" title="<?php echo $this->__('Is New Card') ?>" value="1" />
    <input type="hidden" id="<?php echo $_code ?>_cc_exp_month" name="payment[cc_exp_month]" title="<?php echo $this->__('Exp Month') ?>" value="" />
    <input type="hidden" id="<?php echo $_code ?>_cc_exp_year" name="payment[cc_exp_year]" title="<?php echo $this->__('Exp Year') ?>" value="" />
    <input type="hidden" id="<?php echo $_code ?>_cc_card_type" name="payment[cc_card_type]" title="<?php echo $this->__('Card Type') ?>" value="" />
    <input type="hidden" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Card Number') ?>" value="" />
<!--    <input name="order[billing_address][country_id]" type="hidden" value="US" />    -->
    <?php if ($this->getSaveCardMode() == 'save'): ?>
        <input type="hidden" id="<?php echo $_code ?>_save_card" name="payment[save_card]" title="<?php echo $this->__('Save Card') ?>" value="1" />
    <?php elseif ($this->getSaveCardMode() == 'no_save'): ?>
        <input type="hidden" id="<?php echo $_code ?>_save_card" name="payment[save_card]" title="<?php echo $this->__('Save Card') ?>" value="0" />
    <?php endif; ?>

    <!-- Empty error container -->
    <li>
        <p id="<?php echo $_code ?>_error" class="error"></p>
    </li>

    <li>
        <div class="input-box">
            <label for="spreedly_number_container"><?php echo Mage::helper('payment')->__('Card Number') ?> <span class="required">*</span></label><br/>
            <div id="spreedly_number_container"></div>
        </div>
    </li>

    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_expiry"><?php echo Mage::helper('payment')->__('Expiry Date') ?> <span class="required">*</span></label><br/>
            <input type="text" id="<?php echo $_code ?>_cc_expiry"
                   class="input-text"
                   title="<?php echo Mage::helper('payment')->__('Expiry Date') ?>"
                   maxlength="255"
            />
        </div>
    </li>

    <li>
        <div class="input-box">
            <label for="spreedly_cvv_container"><?php echo Mage::helper('payment')->__('CVV') ?> <span class="required">*</span></label><br/>
            <div id="spreedly_cvv_container"></div>
        </div>
    </li>

    <?php echo $this->getChildHtml() ?>

    <?php if($this->getSaveCardMode() == 'use_checkbox'): ?>
        <li id="<?php echo $_code ?>_cc_save_card_div">
            <div class="input-box">
                <label for="<?php echo $_code ?>_save_card"><?php echo Mage::helper('payment')->__('Save My Card') ?></label><br/>
                    <input type="hidden" title="<?php echo $this->__('Save Card') ?>" name="payment[save_card]" value="0" />
                    <input type="checkbox" title="<?php echo $this->__('Save Card') ?>" class="checkbox"
                           id="<?php echo $_code ?>_save_card" name="payment[save_card]"
                           value="1" <?php if($this->getSaveCard()): ?>checked<?php endif; ?> />
            </div>
        </li>
    <?php endif; ?>

</ul>
