<?php
/**
 * Copyright (c) 2009-2011 Icommerce Nordic AB
 *
 * Icommerce reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Icommerce, except as provided by licence. A licence
 * under Icommerce's rights in the Program may be available directly from
 * Icommerce.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Icommerce
 * @package     Icommerce_
 * @copyright   Copyright (c) 2009-2011 Icommerce Nordic AB
 */
?>
<?php $itemType = $this->getItemType() ?>

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <?php
            $page = Mage::getModel('pagemanager/page')->getPage($_SESSION['page_id']);
            ?>
            <td><h3><?php echo $this->__('Add category to page: ').$page['name']?></h3></td>
            <td class="a-right">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="addcategory_form" enctype="multipart/form-data" name="addcategory_form" method="post" action="<?php echo $this->getUrl('*/*/savecategory')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <input name="addcategoryform[type]" type="hidden" value="<?php echo $itemType['value'] ?>" />
        <input name="addcategoryform[row_id]" type="hidden" value="<?php echo $this->getRequest()->getParam('id') ?>" />
        <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Enter the category information below')?></h4></div>
        <fieldset id="my-fieldset" class="fieldset-wide">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Title')?> <span class="required">*</span></td>
                    <td class="value"><input class="input-text required-entry" name="addcategoryform[title]" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Category id')?></td>
                    <td class="value"><input class="input-text" name="addcategoryform[category_id]" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Status')?> <span class="required">*</span></td>
                    <td class="value">
                        <select name="addcategoryform[status]">
                            <?php $statuses = Mage::helper('pagemanager')->getStatuses(); ?>
                            <?php foreach($statuses as $key => $title): ?>
                            <option value="<?php echo $key?>"><?php echo $this->__($title)?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Position')?></td>
                    <td class="value"><input class="input-text" name="addcategoryform[position]" style="width:30px;" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var addcategoryForm = new varienForm('addcategory_form');
</script>
