<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Menu
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */
?>
<li class="<?php echo $this->getMenuItemClass() ?>">
    <?php if ($this->shouldShowLink()): ?>
        <?php // moved before link due to resizing some-times hiding the buttons -- might be a browser glitch ?>
        <?php if ($this->shouldShowChildren()): ?>
            <button class="toggle-sub-menu"><span class="<?php echo $this->isInCurrentPath() ? 'icon-minus' : 'icon-plus' ?>"></span><span class="sr-only"><?php echo $this->__('Toggle') ?></span></button>
        <?php endif; ?>
        <a href="<?php echo $this->getItemUrl() ?>" class="<?php echo $this->getLinkClass() ?>"><?php echo $this->getItemLabel() ?></a>
        <?php echo $this->getChildHtmlByLevel('menu.item.after.link') ?>
    <?php endif ?>
    <?php if ($this->shouldShowChildren()): ?>
        <ul class="<?php echo $this->getChildListClass() ?>">
            <?php echo $this->renderChildren('main') ?>
            <?php echo $this->renderGroupChildren('footer') ?>
        </ul>
    <?php endif ?>
</li>