<div class="sweettooth-quick-launch-success">
    <h1>Your program is launched. Congratulations!</h1>
    <span class="subtitle">Here are some important things to know:</span>
    <ol>
        <li>
            <span>1. Customers can now earn and spend points on your store.</span>
            <div class="screenshots">
                <img class="left" src="<?php echo $this->getSkinUrl('rewards/images/quickLaunch/earning.png'); ?>" alt="Earning Points" />
                <img class="right" src="<?php echo $this->getSkinUrl('rewards/images/quickLaunch/spending.png'); ?>" alt="Spending Points" />
            </div>
        </li>
        <li>
            <span>2. You can modify your program's rules at any time.</span>
            <div class="screenshots">
                <img class="left" src="<?php echo $this->getSkinUrl('rewards/images/quickLaunch/menu.png'); ?>" alt="Change Rules" />
                <img class="right" src="<?php echo $this->getSkinUrl('rewards/images/quickLaunch/rule-view.png'); ?>" alt="Rules View" />
            </div>
        </li>
        <li>
            <span>3. You can add other ways for customers to earn points.</span>
            <div class="screenshots">
                <img class="left" src="<?php echo $this->getSkinUrl('rewards/images/quickLaunch/path.png'); ?>" alt="Behavior Rules" />
                <img class="right larger" src="<?php echo $this->getSkinUrl('rewards/images/quickLaunch/behavior.png'); ?>" alt="Actions" />
            </div>
        </li>
    </ol>
    <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/dashboard/index'); ?>" title="Dashboard">
        <button type="button">Go To Dashboard</button>
    </a>
</div>