<?php

  $helper = Mage::helper('pagemanager');

  $currentproduct = Mage::registry('current_product');
  $pageId = $currentproduct->getPagemanagerPage();
  if(!isset($pageId)){
        $pageId = 0;
  }

  $rows = $this->getPageRows($pageId);
?>

<?php if(is_array($rows) && count($rows) > 0): ?>
<?php

	/** The $row variable contains the following keys
	 * ------------------------------------------------
	 * $item['id']
	 * $item['page_id']
	 * $item['status']
	 * $item['created_on']
	 * $item['created_by']
	 * $item['position']
	 * $item['type']

	*/

	/** The $item variable contains the following keys
	 * ------------------------------------------------
	 //For All
	 * $item['id']
	 * $item['page_id']
	 * $item['row_id']
	 * $item['type']
	 * $item['status']
	 * $item['created_on']
	 * $item['created_by']
	 * $item['position']
	 * $item['visibility']

	 //For Image
	 * $item['filename']
	 * $item['image_alt']
	 * $item['title']
	 * $item['image_text']
	 * $item['link']
	 * $item['link_target']

	 //For HTML
	 * $item['page_content']

	 //For Toplist
	 * $item['category_id']
	 * $item['products_per_row']
	 * $item['total_products']
	 * $item['sort_by']
	 * $item['toplist']

	 //For Slideshow
	 * $item['slideshow']

	*/

   	$rowIterator = 0;
    echo '<div class="pagemanager page-id-'. $this->getPageId() .'">';
	foreach($rows as $row):

		// Load items
		$items = $this->getPageItems($row['id']);

		// Get row type
		$rowtype = $row['type'];

		if(is_array($items) && count($items) > 0):
			echo '<ul class="row-'.$rowIterator.' '.$helper->getRowTypeClass($rowtype).'">';

			$itemIterator = 0;
			foreach($items as $item):
				if($rowtype > $itemIterator):

					$firstClass = ''; if($itemIterator == 0): $firstClass = ' first'; endif;
					$lastClass = ''; if($rowtype == ($itemIterator+1)): $lastClass = ' last'; endif;

					echo '<li class="'.$item['type'].' item'.$firstClass.$lastClass.'">';
					// If HTML
					if($item['type'] == 'html' || $item['type'] == 'widget'):
						echo Icommerce_Cms::processBlockDirectives($item['page_content']);

					// If Image
					elseif($item['type'] == 'image'):
						if(!empty($item['link'])):
	                        echo '<a href="' . $item['link'] .'"' . $target .'>';
	                    endif;
	
	                    echo '<img src="' . $helper->getImageUrl($item) . '" alt="' .$item['image_alt']. '" />';
	
	                    if(!empty($item['link'])):
	                        echo '</a>';
	                    endif;						

					// If Toplist
					elseif($item['type'] == 'toplist'):

						$toplistArray = array(	"category_id" => $item['category_id'],
												"num_get" => $item['total_products'],
												"attrib_sort" => $item['sort_by'],
												"attribs_select" => "*",
                                                "page_content" => $item['page_content']
                        );

						echo Icommerce_Layout::getBlockHtml("selectedproducts/collection","selectedproducts/".$helper->getToplistTemplate($item['toplist']),$toplistArray);

            		// If Slideshow
					elseif($item['type'] == 'slideshow'):
						echo Icommerce_Layout::getBlockHtml("slideshow/view","slideshow/view.phtml",array(
            "slideshow_id" => $item['slideshow'], "name" => "slideshow"));

            		// If Heading
					elseif($item['type'] == 'heading'):
						echo '<'.$item['heading'].'>'.$item['title'].'</'.$item['heading'].'>';

					endif;
					echo '</li>';

				endif;
			$itemIterator++;
			endforeach;

			echo "</ul>";

		$rowIterator++;
		endif;

	endforeach;
	echo '</div>';
?>

<?php endif; ?>