<?php $_helper = Mage::helper('hylete'); ?>
<?php $_product = Mage::registry('current_product'); ?>

<?php if ($_sizeGuideHtml = $_helper->getSizeguideHtml($_product)): ?>
    <div data-togglecontent="sizeguide" data-togglegroup="productpage" class="sizeguide">
        <p>
            <a data-togglelink="sizeguide" data-togglegroup="productpage" class="underline fancybox-close"><span><?php echo $this->__('close'); ?></span></a>
            <?php echo $_product->getSizeguideText(); ?>
        </p>

        <?php echo $_sizeGuideHtml; ?>
    </div>
<?php endif; ?>