<?php $_helper = Mage::helper('hylete'); ?>
<?php $_product = Mage::registry('current_product'); ?>
<?php $_showNotifyMe = $_helper->showNotifyMe($_product); ?>
<?php $_sizeGuideHtml = $_helper->getSizeguideHtml($_product); ?>

    <p class="sizes">
        <?php if ($_sizeGuideHtml): ?>
            <a data-togglelink="sizeguide" data-togglegroup="productpage">
                <i class="fal fa-ruler"></i>
                <span class="underline"><?php echo $this->__('fit & size guide'); ?></span>
            </a>
        <?php endif; ?>

        <?php if ($_showNotifyMe): ?>
            <?php echo ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) ? $this->__('size not available?') : $this->__('not available?') ?>
            <a data-togglelink="getnotified" data-togglegroup="productpage"
               class="underline"><?php echo $this->__('get notified'); ?></a>
        <?php endif; ?>
    </p>

<?php if ($_sizeGuideHtml): ?>
    <div data-togglecontent="sizeguide" data-togglegroup="productpage" class="sizeguide">
        <p>
            <a data-togglelink="sizeguide" data-togglegroup="productpage"
               class="underline"><?php echo $this->__('close'); ?></a>
            <?php echo $_product->getSizeguideText(); ?>
        </p>
        <?php echo $_sizeGuideHtml; ?>
    </div>
<?php endif; ?>