<?php $_product = Mage::registry('current_product');?>
<?php $_helper = Mage::helper('hylete'); ?>

<ul class="tabs">
	<?php foreach ($_helper->getProductTabsCmsBlocks($_product) as $_block): ?>
		<?php if(substr($_block->getIdentifier(), 0, 17)  == 'product_cms_video') { ?>
        <li>
            <a data-togglelink="<?php echo $_block->getIdentifier(); ?>" data-togglegroup="tabs">watch video<span class="fa fa-plus"></a>
            <div data-togglecontent="<?php echo $_block->getIdentifier(); ?>" data-togglegroup="tabs">
				<?php echo $_block->getContent(); ?>
            </div>
        </li>
	<?php } endforeach; ?>
    <li>
        <a data-togglelink="details" data-togglegroup="tabs"><?php echo $this->__('description & details'); ?> <span class="fa fa-plus"></a>
        <div data-togglecontent="details" data-togglegroup="tabs">
            <div class="description"><?php echo $_product->getDescription(); ?></div>
            <?php echo $_product->getShortDescription(); ?>
        </div>
    </li>
    <li>
        <a data-togglelink="material" data-togglegroup="tabs"><?php echo $this->__('material'); ?> <span class="fa fa-plus"></a>
        <div data-togglecontent="material" data-togglegroup="tabs">
            <?php echo Icommerce_Default::getOptionValue($_product, 'material'); ?>
        </div>
    </li>
    <?php foreach ($_helper->getProductTabsCmsBlocks($_product) as $_block): ?>
	    <?php if(substr($_block->getIdentifier(), 0, 17) != 'product_cms_video') { ?>
        <li>
            <a data-togglelink="<?php echo $_block->getIdentifier(); ?>" data-togglegroup="tabs"><?php echo $_block->getTitle(); ?> <span class="fa fa-plus"></a>
            <div data-togglecontent="<?php echo $_block->getIdentifier(); ?>" data-togglegroup="tabs">
                <?php echo $_block->getContent(); ?>
            </div>
        </li>
    <?php  } endforeach; ?>
</ul>