<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SubscribePro
 * @package   SubscribePro_Autoship
 * @author    Subscribe Pro Support <support@subscribepro.com>
 * @copyright 2009-2020 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>

<?php
use SubscribePro\Service\PaymentProfile\PaymentProfileInterface;
// Get saved credit cards
$paymentProfiles = $this->getCustomerPaymentProfiles();
/** @var PaymentProfileInterface $selectedPaymentProfile */
$selectedPaymentProfile = $this->getPaymentProfile();
?>

<form id="payment-form-<?php echo $this->getSubscription()->getId() ?>" class="payment-form" action="<?php echo Mage::getUrl('autoship/mysubscriptions/change', array('_secure' => true)) ?>">
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
<input type="hidden" name="subscription_id" id="subscription_id_<?php echo $this->getSubscription()->getId() ?>"
    value="<?php echo $this->getSubscription()->getId() ?>"/>
<fieldset>
<dl>

<?php
/** @var PaymentProfileInterface $paymentProfile */
foreach ($paymentProfiles as $paymentProfile):
    ?>
<dt>
	<?php
	$curMethodName = $paymentProfile->getCustomerFacingName();
	$isSelected = $paymentProfile->getId() == $selectedPaymentProfile->getId();
	?>
	<input
		id="payment_profile_id_<?php echo $paymentProfile->getId() ?>"
		value="<?php echo $paymentProfile->getId() ?>"
		type="radio" name="payment_profile_id"
		title="<?php echo $this->htmlEscape($curMethodName) ?>"
		onclick=""
		class="radio"
		<?php if($isSelected): ?>checked="checked"<?php endif; ?>
	/>
	<label for="payment_profile_id_<?php echo $paymentProfile->getId() ?>">
		<?php echo $this->escapeHtml($curMethodName) ?>
	</label>
</dt>
<dd>
</dd>
<?php
endforeach;
?>

</dl>

<div class="buttons-set" id="billing-buttons-container">
<button type="submit" title="<?php echo $this->__('Continue') ?>" class="button"><span><span><?php echo $this->__('Continue') ?></span></span></button>
<span class="please-wait" id="billing-please-wait" style="display:none;">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Updating...') ?>" title="<?php echo $this->__('Updating...') ?>" class="v-middle" /> <?php echo $this->__('Updating...') ?>
</span>
</div>

</fieldset>
</form>
