<?php
// I experienced a big with rowtype. $rowType is a array, so this code isnt correct or handled that way.
// I have commented away the row that crashed (hidden field below)
// Magnus
?>
<?php
    $helper = Mage::helper('pagemanager');
    $rowType =  Mage::getModel('pagemanager/row')->getRowType();
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
        	<?php
        		$page = Mage::getModel('pagemanager/page')->getPage($_SESSION['page_id']);
        	?>
            <td><h3><?php echo $this->__('Add row to page: ').$page['name']?></h3></td>
            <td class="a-right">
            	<?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="add_form" enctype="multipart/form-data" name="add_form" method="post" action="<?php echo $this->getUrl('*/*/save')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />

        <input name="addform[type]" type="hidden" value="<?php //echo $rowType['value'] ?>" />

        <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Enter the row information below')?></h4></div>
        <fieldset id="my-fieldset" class="fieldset-wide">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Rowtype')?> <span class="required">*</span></td>
                    <td class="value">
                    	<select name="addform[type]">
                    		<?php foreach($rowType as $key => $title): ?>
	                    		<option value="<?php echo $title['value']?>"><?php echo $this->__($title['label'])?></option>
                    		<?php endforeach; ?>
                    	</select>
                    </td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Status')?> <span class="required">*</span></td>
                    <td class="value">
                    	<select name="addform[status]">
                    		<?php $statuses = Mage::helper('pagemanager')->getStatuses(); ?>
                    		<?php foreach($statuses as $key => $title): ?>
	                    		<option value="<?php echo $key?>"><?php echo $this->__($title)?></option>
                    		<?php endforeach; ?>
                    	</select>
                    </td>
                </tr>
                <?php if ($helper->useRowClassnames() && $helper->hasPredefClasses() ): ?>
                    <tr>
                        <?php $predefClassnames = $helper->getPredefRowClasses(); ?>
                        <td class="label"><?php echo $this->__('Predefined classnames')?> <span class="required">*</span></td>
                        <td class="value">
                            <select name="addform[predefined_classnames][]" multiple="multiple">
                                <?php foreach($predefClassnames as $predefClass): ?>
                                    <option value="<?php echo $predefClass ?>">
                                        <?php echo $predefClass ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($helper->useRowClassnames()): ?>
                    <tr>
                        <td class="label"><?php echo $this->__('Classnames (separate by space)')?></td>
                        <td class="value"><input class="input-text" name="addform[classnames]" value="" /></td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <td class="label"><?php echo $this->__('Position')?></td>
                    <td class="value"><input class="input-text" name="addform[position]" style="width:30px;" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var addForm = new varienForm('add_form');
</script>
