<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Rules
 */
?>
<?php
$showDetails = Mage::getStoreConfig('amrules/breakdown_settings/open_discount_label');
?>
<?php if (is_array($this->getTotal()->getFullInfo())) : ?>
<?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
    <tr class="summary-details-amrules summary-details<?php if($showDetails):?>show-details<?php endif?>"
        <?php if(!$showDetails):?> style="display:none;"<?php endif?>>
        <td class="a-right amrules-discount-wrapper" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $info['label']; ?>
            <br />
        </td>
        <td class="a-right amrules-amount" rowspan="1">
            -<?php echo $this->helper('checkout')->formatPrice($info['amount']); ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php endif; ?>
<tr class="summary-total <?php if($showDetails):?>show-details<?php endif?>" onclick="expandDetails(this, '.summary-details-amrules')" >
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
        <?php if (is_array($this->getTotal()->getFullInfo())) : ?>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                <strong>
            <?php endif; ?>
            <div class="summary-collapse amrules-discount-label"><?php echo $this->__('Total Discount(s)') ?><span class="fa fa-angle-up"></span></div>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                </strong>
            <?php endif; ?>
        <?php else: ?>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                <strong>
            <?php endif; ?>
                <div class="amrules-discount-label amrules-discount-label-no-link"><?php echo $this->__('Total Discount(s)') ?></div>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                </strong>
            <?php endif; ?>
        <?php endif;?>
    </td>
    <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right <?php echo is_array($this->getTotal()->getFullInfo()) ? '' : 'amrules-discount-label-no-link' ?>">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
</tr>
