<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
        	<?php 
        		$page = Mage::getModel('pagemanager/page')->getPage($_SESSION['page_id']);
        	?>
            <td><h3><?php echo $this->__('Add HTML in page: ').$page['name']?></h3></td>
            <td class="a-right">
            	<?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit"> 
    <form action="<?php echo $this->getUrl('*/*/savehtml')?>" method="post" id="addhtml_form">
    	<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    	<?php echo $this->getForm() ?>
	</form>
</div>
<script type="text/javascript">
    var addhtmlForm = new varienForm('addhtml_form');
</script>
