<?php
$_helper = Mage::helper('headercart');

// Get totals
$_totals = $_helper->getTotals();
$_subtotal = $_totals['subtotal'];
$_grandTotal = $_totals['grand_total'];

// Get cart quantity
$_cartQty = $_helper->getCartQty($this->getSummaryCount());

//Get recent items and and calculate the correct quantity of "Viewing x items"
$_items = $this->getItems();
$_numItems = $_helper->getQtyOfRecentItems($_items);
/** @var Mage_Core_Model_Store $_quoteStore */
$_quoteStore = $this->helper('checkout')->getQuote()->getStore();
$_notEmpty = $_cartQty > 0;

$_pointSummaryBlock = Mage::helper('catalog')->isModuleEnabled('TBT_Rewards')
    ? Mage::getBlockSingleton('rewards/special_header')->getPointsSummary()
    : '';

/** @var Mage_Customer_Model_Session $_customerSession */
$_customerSession = Mage::getSingleton('customer/session');
$_isLoggedIn = $_customerSession->isLoggedIn();

$_hyleteInfoEcomm = array(
    'ecomm_logged_in' => $_isLoggedIn ? '1' : '0',
    'ecomm_group_id'  => '0',
    'ecomm_gender' => '',
    'ecomm_customer_id' => '',
    'ecomm_customer_email' => '',
);
$_hyleteInfoAccount = array(
    'customer_logged_in' => (int)$_isLoggedIn,
    'customer_group_id' => 0,
    'customer_gender' => '',
    'customer_id' => '',
    'customer_email' => '',
);

if ($_isLoggedIn) {
    /** @var Mage_Customer_Model_Customer $_customer */
    $_customer = $_customerSession->getCustomer();
    //$_hyleteInfoAccount['customer_logged_in'] = 1;
    $_hyleteInfoAccount['customer_group_id'] = $_customer->getGroupId();
    $_hyleteInfoAccount['customer_gender'] = $_customer->getGender();
    $_hyleteInfoAccount['customer_id'] = $_customer->getId();
    $_hyleteInfoAccount['customer_email'] = $_customer->getEmail();
    $_hyleteInfoAccount['customer_firstname'] = $_customer->getFirstname();
    $_hyleteInfoAccount['customer_lastname'] = $_customer->getLastname();

    //$_hyleteInfoEcomm['ecomm_logged_in'] = 1;
    $_hyleteInfoEcomm['ecomm_group_id'] = (string)$_customer->getGroupId();
    $_hyleteInfoEcomm['ecomm_gender'] = $_customer->getGender();
    $_hyleteInfoEcomm['ecomm_customer_id'] = $_customer->getId();
    $_hyleteInfoEcomm['ecomm_customer_email'] = $_customer->getEmail();
}

?>

<div class="headercart <?php if ($_notEmpty): ?>not-empty<?php endif; ?>" id="<?php if ($_notEmpty): ?>headercart<?php else: ?>headercart-disabled<?php endif; ?>">
    <div class="top">
        <a href="<?php echo $this->getUrl('checkout/cart');?>" class="cart-button js-cart-open fade-icon">
            <span class="sprite-cart"></span>
            <span class="cart-badge fade-icon"><?php echo ($_cartQty > 0) ? $_cartQty : '';?></span>
            <span class="hidden-inline-block-xs hidden-inline-block-sm"><?php echo $this->__('cart');?></span>
        </a>
    </div>
    <?php if (Mage::helper('hylete')->showHeaderCartDropDown()): ?>
        <div id="recently-added-container" class="showcart">
            <div class="header">
                <div class="minicart-cart">
                    <span class="sprite-cart"></span>
                    <span class="cart-badge"><?php echo ($_cartQty > 0) ? $_cartQty : '';?></span>
                </div>
                <?php if ($_notEmpty) : ?>
                    <a class="view-cart" href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('view cart & checkout') ?></a>
                <?php endif; ?>
                <span class="sprite-close js-cart-close"></span>
            </div>
            <div class="headercart-inner clearfix <?php if ($_isLoggedIn) { echo 'logged-in'; } ?>">
                <?php if(count($_items)): ?>
                    <ol id="cart-sidebar" class="mini-products-list">
                        <?php foreach($_items as $_item): ?>
                            <?php echo $this->getItemHtml($_item) ?>
                        <?php endforeach; ?>
                    </ol>
                    <div class="minicart-footer">
                        <div class="minicart-footer-wrapper totals">
                            <?php echo $this->getLayout()->createBlock('checkout/cart_totals')->setTemplate('checkout/cart/totals.phtml')->toHtml() ?>
                            <button class="button button-co" onclick="setLocation('<?php echo $this->getUrl('checkout/cart'); ?>')"><?php echo $this->__('view cart & checkout') ?></button>
                        </div>
                    </div>
                <?php else: ?>
                    <p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                <?php endif ?>
            </div>
        </div>
    <?php endif; ?>
    <input type="hidden" id="sweet-tooth-points-value" name="sweet-tooth-points-value" value="<?php echo ($_pointSummaryBlock != '') ? $this->__("(%s)",str_replace(array('Points'),array('points'),$_pointSummaryBlock)) : '' ?>"/>

    <div class="headercart-filter"></div>
</div>
<script>
    (function (){
        if (typeof hyleteInfo == 'undefined'){
            hyleteInfo = {};
        }
        hyleteInfo.account = <?php echo Zend_Json::encode($_hyleteInfoAccount) ?>;
        hyleteInfo.ecomm = <?php echo Zend_Json::encode($_hyleteInfoEcomm) ?>;
        hyleteInfo.cart = <?php echo Zend_Json::encode(array('qty' => $_cartQty, 'grand_total' => $_grandTotal)) ?>;
    })();
</script>