<?php
    $helper = Mage::helper('pagemanager');
    $row = $this->getRow();
    $rowType = $this->getRowType();
?>

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Edit row: ')?><?php echo $row['id'] ?></h3></td>
            <td class="a-right">
            	<?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="edit_form" enctype="multipart/form-data" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/update')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<input name="editform[id]" type="hidden" value="<?php echo $row['id'] ?>" />
		<input name="editform[type]" type="hidden" value="<?php echo $row['type'] ?>" />
        <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Edit the row information below')?></h4></div>
        <fieldset id="my-fieldset"  class="fieldset-wide">
            <table cellspacing="0" class="form-list">
            	<tr>
            		<td class="label"><?php echo $this->__('Rowtype')?></td>
            		<td class="value"><?php echo $helper->getRowTypeName($row['type']) ?></td>
            	</tr>
                <tr>
                    <td class="label"><?php echo $this->__('Status')?> <span class="required">*</span></td>
                    <td class="value">
                    	<select name="editform[status]">
                    		<?php $statuses = Mage::helper('pagemanager')->getStatuses(); ?>
                    		<?php foreach($statuses as $key => $title): ?>
								<option value="<?php echo $key?>"<?php echo ''.($row['status'] == $key ? ' selected="selected"' : '') ?>><?php echo $this->__($title)?></option>
                    		<?php endforeach; ?>
                    	</select>
                    </td>
                </tr>
                <?php if ($helper->useRowClassnames() && $helper->hasPredefClasses()): ?>
                <tr>
                    <?php
                        $predefClassnames = $helper->getPredefRowClasses();
                        $classnames = explode(' ', $row['classnames']);
                    ?>
                    <td class="label"><?php echo $this->__('Predefined classnames')?> <span class="required">*</span></td>
                    <td class="value">
                        <select name="editform[predefined_classnames][]" multiple="multiple">
                            <?php foreach($predefClassnames as $predefClass): ?>
                                <option value="<?php echo $predefClass ?>"<?php echo in_array($predefClass, $classnames)  ? ' selected="selected"' : '' ?>>
                                    <?php echo $predefClass ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <?php endif; ?>
                <?php if ($helper->useRowClassnames()): ?>
                <?php
                    $classnames = $helper->unsetArrayDuplicates($predefClassnames, $classnames);
                    $classnames = implode(' ', $classnames);
                ?>
                <tr>
                    <td class="label"><?php echo $this->__('Classnames (separate by space)')?></td>
                    <td class="value"><input class="input-text" name="editform[classnames]" value="<?php echo $classnames?>" /></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <td class="label"><?php echo $this->__('Position')?></td>
                    <td class="value"><input class="input-text" name="editform[position]" value="<?php echo $row['position']?>" style="width:30px;" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editform = new varienForm('edit_form');
</script>
