<script type="text/javascript">
    if($('advanced_modules_disable_output') != undefined ) {
         $('advanced_modules_disable_output').getElementsBySelector('#TBT_Common').first().insert({
          after: "<p class='note' style='color:red'><?php echo $this->helper("rewards")->__("Please do not disable TBT_Common, even if you completely disable output for a specific store. For more info, please check <a href='http://help.sweettoothrewards.com/article/138-i-disabled-sweet-tooth-through-the-backend-configuration-but-there-are-still-happening-with-sweet-tooth-in-the-frontend' target='_blank'>here.</a>");?></p>"
     });
    }
</script>
