<?php
/**
 * Copyright (c) 2009-2013 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Blog
 * @copyright   Copyright (c) 2009-2013 Vaimo AB
 * @author      Tobias Wiking
 */
?>
<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$currentUrl = $this->helper('core/url')
        ->getCurrentUrl();
$_helperBlog = $this->helper('blog');
$_helperHylete = $this->helper('hylete');
$productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
$_productCategory = $_helperHylete->getCategory();
$_subCategories = $_productCategory->getChildren();
$imageWidth = 770;
?>
<?php echo $this->getLayout()
        ->getBlock('breadcrumbs')
        ->toHtml(); ?>
<section>
    <div class="col-md-8 left-col">
        <article class="blog-full-length">
            <h1><?php echo $productName ?></h1>

            <img class="full-img large-image" src="<?php echo $this->helper('catalog/image')
                    ->init($_product, 'image')
                    ->keepAspectRatio(TRUE)
                    ->keepFrame(FALSE)
                    ->resize($imageWidth); ?>"/>
            <img class="full-img small-image" src="<?php echo $this->helper('catalog/image')
                    ->init($_product, 'image')
                    ->keepAspectRatio(TRUE)
                    ->keepFrame(FALSE)
                    ->resize(380); ?>"/>

            <div class="post-content">
                <label class="date-label"><?php echo $_helperBlog->getPublishDate($_product, "MMM d, YYYY") ?>
                </label>

                <p class="blog-content">
                    <?php $content = $_helper->productAttribute($_product, $_product->getBlogContent(), 'blog_content') ?>
                    <?php echo $content; ?>
                </p>
            </div>
        </article>

        <?php echo $this->getChildHtml('blog_related_products'); ?>
    </div>
    <div class="col-md-4 right-col">
        <?php echo $this->getChildHtml('blog.right.column') ?>
    </div>
</section>