
<?php $item = $this->getItem(); ?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <?php
            $slideshow = Mage::getModel('slideshowmanager/slideshow')->getSlideshow($_SESSION['slideshow_id']);
            ?>
            <td><h3><?php echo $this->__('Edit Layered HTML in slideshow: ').$slideshow['name']?></h3></td>
            <td class="a-right">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form action="<?php echo $this->getUrl('*/*/updatelayeredhtml')?>" method="post" id="editlayeredhtml_form" enctype="multipart/form-data">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <input name="id" type="hidden" value="<?php echo $item['id'] ?>" />
        <?php echo $this->getForm() ?>
    </form>
</div>
<script type="text/javascript">
    var editlayeredhtmlForm = new varienForm('editlayeredhtml_form');
</script>
