<?php $itemType = $this->getItemType() ?>

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
        	<?php 
        		$page = Mage::getModel('pagemanager/page')->getPage($_SESSION['page_id']);
        	?>
            <td><h3><?php echo $this->__('Add H1 to page: ').$page['name']?></h3></td>
            <td class="a-right">
            	<?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="addheading_form" enctype="multipart/form-data" name="addheading_form" method="post" action="<?php echo $this->getUrl('*/*/saveheading')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <input name="addheadingform[type]" type="hidden" value="<?php echo $itemType['value'] ?>" />
        <input name="addheadingform[row_id]" type="hidden" value="<?php echo $this->getRequest()->getParam('id') ?>" />
        <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Enter the H1 information below')?></h4></div>
        <fieldset id="my-fieldset" class="fieldset-wide">
            <table cellspacing="0" class="form-list">
            	<tr>
                    <td class="label"><?php echo $this->__('Heading')?> <span class="required">*</span></td>
                    <td class="value"><input class="input-text required-entry" name="addheadingform[title]" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Heading type')?> <span class="required">*</span></td>
                    <td class="value">
                    	<select name="addheadingform[heading]">
                    		<?php $headings = Mage::helper('pagemanager')->getHeadings(); ?>
                    		<?php foreach($headings as $key => $title): ?>
	                    		<option value="<?php echo $title['value']?>"><?php echo $this->__($title['label'])?></option>
                    		<?php endforeach; ?>
                    	</select>
                    </td>
                </tr> 
                <tr>
                    <td class="label"><?php echo $this->__('Status')?> <span class="required">*</span></td>
                    <td class="value">
                    	<select name="addheadingform[status]">
                    		<?php $statuses = Mage::helper('pagemanager')->getStatuses(); ?>
                    		<?php foreach($statuses as $key => $title): ?>
	                    		<option value="<?php echo $key?>"><?php echo $this->__($title)?></option>
                    		<?php endforeach; ?>
                    	</select>
                    </td>
                </tr>    
                <tr>
                    <td class="label"><?php echo $this->__('Position')?></td>
                    <td class="value"><input class="input-text" name="addheadingform[position]" style="width:30px;" /></td>
                </tr>            
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var addheadingForm = new varienForm('addheading_form');
</script>
