<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Hylete
 * @author      Scott Kennerly <skennerly@hylete.com>
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */
?>
<?php
/** @var Vaimo_Hylete_Block_TrackingScripts $this */
$_pageType = $this->getDynamicRemarketingPageType();
$_accumulatedProductData = $this->getDynamicRemarketingProductData($_pageType);

$_dataLayerData = array(
	'ecomm_prodid' => $_accumulatedProductData['product_skus_array'],
	'ecomm_product_gender' => isset($_accumulatedProductData['product_gender']) ? $_accumulatedProductData['product_gender'] : '',
	'ecomm_totalvalue' => $_accumulatedProductData['total_price'],
	'ecomm_pagetype' => $_pageType,
);

?>
<script>
    (function ($) {
        dataLayerEcommData = <?php echo Zend_Json::encode($_dataLayerData) ?>;

        if (typeof hyleteInfo !== 'undefined') {
            if (hyleteInfo.ecomm) {
                dataLayerEcommData = $.extend({}, dataLayerEcommData, hyleteInfo.ecomm);
            }

            if (hyleteInfo.account) {
                dataLayerEcommData = $.extend({}, dataLayerEcommData, hyleteInfo.account);
            }

            if (hyleteInfo.cart) {
                dataLayerEcommData = $.extend({}, dataLayerEcommData, hyleteInfo.cart);
            }
        }
        if (typeof dataLayer != "undefined") {
            dataLayer.push(dataLayerEcommData);
        }

    })(jQuery);

</script>