<?php
/*
 * Collect data for the analytics
 */
$_json = Mage::helper('googleaddons')->getTransactionEventJSON();
?>
<?php if (!empty($_json)): ?>
    <script>
        if (typeof dataLayer!='undefined') {
            //We are calling method push() of object dataLayer only if object exists to avoid js error in frontend
            dataLayer.push(<?php echo $_json; ?>);
        }
    </script>

    <script>
        /*console.log("set PurchaseEvent");
		var intPurchase=setInterval(function(){
		  if(typeof(window.setFbqData)=="undefined" || typeof(window.writeFbqFunc)=="undefined"){return;}
		  clearInterval(intPurchase);
		  window.setFbqData();
		  //window.writeFbqFunc(function(){*/

        var json = "";
        json = <?php echo $_json; ?>;
        var productsIds;
        if(json.transactionProducts.length==1){
            //console.log("fb_product_id: " + json.transactionProducts[0].parent_sku);
            productsIds=json.transactionProducts[0].parent_sku;
        }else{
            productsIds="[";
            var i;
            for(i=0;i<json.transactionProducts.length;i++){
                productsIds+="'"+json.transactionProducts[i].parent_sku+"',";
            }
            productsIds=productsIds.substr(0,productsIds.length-1)+"]";
            //console.log("fb_product_id: " + productsIds);
        }

        //console.log("fb_tran_id: " + json.transactionId);
        //console.log("fb_tran_total: " + json.transactionTotal);
        //console.log("fb_tran_currency: " + json.transactionCurrency);

        var objPurchase={
            product_catalog_id: 633438867150935,
            content_type: 'product',
            content_ids: productsIds,
            value: json.transactionTotal,
            currency: json.transactionCurrency,
            order_id: json.transactionId
        };
        //console.log("purchase fbk");
        fbq('track', 'Purchase', objPurchase);
        /*//});
	  },10);*/
    </script>
<?php endif; ?>