<?php echo $this->getChildHtml('coupon_before') ?>
<div id="coupon-discount" class="firecheckout-section">
    <div class="block-title b-discount__title"><span><?php echo $this->__('Promo code') ?></span></div>
    <div class="discount-form" id="discount-code">
        <?php
            echo $this->getMessagesBlock()->getGroupedHtml();
            $this->getMessagesBlock()->getMessageCollection()->clear();
        ?>
        <label for="coupon-code" class="b-discount__subtitle"><?php echo $this->__('Enter a promo code if you have one') ?></label>
        <div class="input-box">
            <input type="hidden" name="coupon[remove]" id="coupon-remove" value="0" />
            <div class="input-field-wrapper">
                <input class="input-text b-discount__input" id="coupon-code" name="coupon[code]" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
            </div>
            <?php if (strlen($this->getCouponCode())) : ?>
                <button type="button" title="<?php echo $this->__('Cancel promo code') ?>" id="coupon-cancel" class="button b-discount__button" value="<?php echo $this->__('Cancel promo code') ?>"><span><span><?php echo $this->__('Cancel promo code') ?></span></span></button>
            <?php else: ?>
                <button type="button" title="<?php echo $this->__('Apply promo code') ?>" id="coupon-apply" class="button b-discount__button" value="<?php echo $this->__('Apply promo code') ?>"><span><span><?php echo $this->__('Apply promo code') ?></span></span></button>
            <?php endif; ?>
        </div>
    </div>
    <script type="text/javascript">
    //<![CDATA[
    $('coupon-apply') && $('coupon-apply').observe('click', function(e) {
        var code = $('coupon-code');
        if (!code.value.length) {
            code.addClassName('required-entry');
            Validation.validate(code);
            code.removeClassName('required-entry');
            return;
        }
        $('coupon-remove').value = "0";
        checkout.setLoadingButton($('coupon-apply'));
        checkout.update(checkout.urls.coupon, {
            'review': 1
        });
    });
    $('coupon-cancel') && $('coupon-cancel').observe('click', function(e) {
        $('coupon-remove').value = "1";
        checkout.setLoadingButton($('coupon-cancel'));
        checkout.update(checkout.urls.coupon, {
            'review': 1
        });
    });
    $('coupon-code').observe('keydown', function(e) {
        if (e.keyCode != 13) {
            return;
        }
        var code = $('coupon-code');
        if (!code.value.length) {
            code.addClassName('required-entry');
            Validation.validate(code);
            code.removeClassName('required-entry');
            return;
        }
        $('coupon-remove').value = "0";
        checkout.setLoadingButton($('coupon-apply'));
        checkout.update(checkout.urls.coupon, {
            'review': 1
        });
    });
    //]]>
    </script>
</div>
<?php echo $this->getChildHtml('coupon_after') ?>
