<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SubscribePro
 * @package   SubscribePro_Autoship
 * @author    Subscribe Pro Support <support@subscribepro.com>
 * @copyright 2009-2020 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php if(Mage::getStoreConfig('autoship_general/general/enabled') == '1'): ?>
<?php $quoteItem = $this->getQuoteItem(); ?>
<?php if ($this->isItemSubscriptionEligible()): ?>
<?php if($this->isTrialProduct() || $this->getSubscriptionOptionMode() == 'subscription_only'): // Subscription Only Mode or Trial Product - Only Subscription Option Allowed ?>
    <div class="subscription-product product-options">
        <?php if ($this->isTrialProduct()): ?><p><?php echo $this->__('Trial Subscription') ?></p><?php endif; ?>
        <ul class="options-list">
            <li>
                <input type="hidden"
                       id="<?php echo $quoteItem->getId() ?>-delivery-option-subscribe"
                       name="cart[<?php echo $quoteItem->getId() ?>][delivery-option]" value="subscribe"
                    />

                <label for="delivery-interval">Delivery every:
                    <select
                            onchange="this.form.submit();"
                            id="<?php echo $quoteItem->getId() ?>-delivery-interval"
                            name="cart[<?php echo $quoteItem->getId() ?>][delivery-interval]"
                            class="">
                        <?php foreach ($this->getIntervals() as $interval): ?>
                            <option value="<?php echo $interval ?>" <?php if($interval == $this->getNewSubscriptionInterval()): ?>selected="selected"<?php endif; ?>>
                                <?php echo $interval ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </label>
            </li>
        </ul>
    </div>
<?php else: // Standard version ?>
    <div class="subscription-product product-options">
        <p><?php echo $this->__('Would you like to receive regular shipments of this item?') ?></p>
        <ul class="options-list">
            <li>
                <input type="radio" onclick="" class="radio"
                       onchange="this.form.submit();"
                       id="<?php echo $quoteItem->getId() ?>-delivery-option-one-time"
                       name="cart[<?php echo $quoteItem->getId() ?>][delivery-option]"
                       value="one-time-delivery"
                       <?php if (!$this->isItemFlaggedToCreateNewSubscription()): ?>checked="checked"<?php endif; ?>
                    />
	            <span class="label">
		            <label for="delivery-option-one-time"><?php echo $this->__("One Time Delivery") ?></label>
	            </span>
            </li>
            <li>
                <input type="radio" onclick="" class="radio"
                       onchange="this.form.submit();"
                       id="<?php echo $quoteItem->getId() ?>-delivery-option-subscribe"
                       name="cart[<?php echo $quoteItem->getId() ?>][delivery-option]" value="subscribe"
                       <?php if ($this->isItemFlaggedToCreateNewSubscription()): ?>checked="checked"<?php endif; ?>
                    />
	            <span class="label">
                    <label for="delivery-option-subscribe"><?php echo $this->__("Regular Delivery") ?></label>
	            </span>

                <label for="delivery-interval"><?php echo $this->__("Delivery every:") ?>
                    <select
                            onchange="this.form.submit();"
                            id="<?php echo $quoteItem->getId() ?>-delivery-interval"
                            name="cart[<?php echo $quoteItem->getId() ?>][delivery-interval]"
                            class="">
                        <?php foreach ($this->getIntervals() as $interval): ?>
                            <option value="<?php echo $interval ?>" <?php if($interval == $this->getNewSubscriptionInterval()): ?>selected="selected"<?php endif; ?>>
                                <?php echo $interval ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </label>
            </li>
        </ul>
    </div>
<?php endif; ?>
<?php endif; ?>
<?php endif; ?>