<?php 
	$helper = Mage::helper('pagemanager');
?>
<?php $item = $this->getItem(); $itemType = $this->getItemType()?>

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Edit image: ')?><?php echo $item['title']?></h3></td>
            <td class="a-right">
            	<?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="editimage_form" enctype="multipart/form-data" name="editimage_form" method="post" action="<?php echo $this->getUrl('*/*/updateimage')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<input name="editimageform[id]" type="hidden" value="<?php echo $item['id'] ?>" />
		<input name="editimageform[type]" type="hidden" value="<?php echo $itemType['value'] ?>" />
        <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Edit the image information below')?></h4></div>
        <fieldset id="my-fieldset"  class="fieldset-wide">
            <table cellspacing="0" class="form-list">
            	<tr>
            		<td><?php echo $this->__('Existing image')?></td>
            		<td class="value"><img src="<?php echo $helper->getImageUrl($item) ?>" height="100" /></td>
            	</tr>
                <tr>
                    <td class="label"><?php echo $this->__('Choose new image')?></td>
                    <td class="value"><input class="input-file" type="file" name="file" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Title')?> <span class="required">*</span></td>
                    <td class="value"><input class="input-text required-entry" name="editimageform[title]" value="<?php echo $item['title']?>" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Image text')?></td>
                    <td class="value"><textarea class="input-text" name="editimageform[image_text]" style="width:200px;height:100px;"><?php echo $item['image_text']?></textarea></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Alt-text')?></td>
                    <td class="value"><input class="input-text" name="editimageform[image_alt]" value="<?php echo $item['image_alt']?>" /></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Link')?></td>
                    <td class="value"><input class="input-text" name="editimageform[link]" value="<?php echo $item['link']?>" /></td>
                </tr> 
                <tr>
                    <td class="label"><?php echo $this->__('Link target')?></td>
                    <td class="value">
                    	<select name="editimageform[link_target]">
                    		<option value="" <?php echo ''.($item['link_target'] == '' ? 'selected="selected"' : '') ?>><?php echo $this->__('Samma fönster'); ?></option>
                    		<option value="_blank" <?php echo ''.($item['link_target'] == '_blank' ? 'selected="selected"' : '') ?>><?php echo $this->__('Nytt fönster'); ?></option>
                    	</select>
                   	</td>
                </tr>   
                <tr>
                    <td class="label"><?php echo $this->__('Status')?> <span class="required">*</span></td>
                    <td class="value">
                    	<select name="editimageform[status]">
                    		<?php $statuses = Mage::helper('pagemanager')->getStatuses(); ?>
                    		<?php foreach($statuses as $key => $title): ?>
								<option value="<?php echo $key?>"<?php echo ''.($item['status'] == $key ? ' selected="selected"' : '') ?>><?php echo $this->__($title)?></option>
                    		<?php endforeach; ?>
                    	</select>
                    </td>
                </tr>    
                <tr>
                    <td class="label"><?php echo $this->__('Position')?></td>
                    <td class="value"><input class="input-text" name="editimageform[position]" value="<?php echo $item['position']?>" style="width:30px;" /></td>
                </tr>            
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editimageform = new varienForm('editimage_form');
</script>
