<!-- Nxt version : 5.3.1  -->
<?php
if($this->allowShowBlock()):
    $id = $this->getNxtId();
    if ($id) :
?>
<script type="text/javascript">

    function nxtAddLoadListener(fn) {
//mozilla and friends
        if (typeof window.addEventListener != 'undefined') {
            window.addEventListener('load', fn, false);
        }
//opera
        else if (typeof document.addEventListener != 'undefined') {
            document.addEventListener('load', fn, false);
        }
//innernetz exploder
        else if (typeof window.attachEvent != 'undefined') {
            window.attachEvent('onload', fn);
        }
//the rest is pretty much for browsers that I doubt your
//CSS or anything else still supports like IE/Mac
        else {
            var oldfn = window.onload;
            if (typeof window.onload != 'function') {
                window.onload = fn;
            }
            else {
                window.onload = function() {
                    oldfn();
                    fn();
                };
            }
        }
    }
    nxtAddLoadListener(function(){
        document.getElementById("search_mini_form").action = "<?php echo $this->getResultUrl(); ?>";
    });

    //Nextopia initialization
    if (typeof nxtOptions !== 'object') {
        var nxtOptions = {};
    }
    if (!nxtOptions.customOptions) {
        nxtOptions.customOptions = {};
    }
    nxtOptions.customOptions.formKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
    nxtOptions.customOptions.groupId = '<?php echo $this->getCustomerGroupCode(); ?>';

</script>
<!-- nextopia ajax initializer -->
<script src='//cdn.nextopia.net/<?php echo $this->getAjaxVersion();?>/<?php echo $id; ?>.js' async></script>
<!-- nextopia ajax  initializer end -->
<?php   else: ?>
<!-- nextopia ajax initializer failed to load due to missing nextopia id -->
<?php   endif; ?>

<?php endif; ?>
