<?php
/**
 * @author    Mediotype Development <diveinto@mediotype.com>
 * @copyright 2018 Mediotype. All Rights Reserved.
 */
?>

<?php $_product = Mage::registry('current_product'); ?>
<?php if ($_product && $_sku = $_product->getSku()): ?>
    <script type="text/x-np-template">
        <div class="nxt-psn-view">
            <span class="sku"><?php echo $_sku ?></span>
        </div>
    </script>
    <?php $_publicId = Mage::getStoreConfig('nextopia_ajax_options/settings/public_client_id') ?>
    <?php $_productInstance = Mage::getStoreConfig('nextopia_product_page/settings/product_recommendation_instance') ?>
    <?php $_key = $_publicId . '-' . $_productInstance; ?>
        <script type="text/javascript">
            var nxt_recs = nxt_recs || [];
            nxt_recs.push(
                [
                    '<?php echo $_key ?>',
                    'skuValue',
                    '<?php echo $_sku ?>'
                ]
            );
            nxt_recs.push([ '<?php echo $_key ?>', 'cache', false]);
        </script>
<?php endif; ?>
