
<script type="text/javascript">
    <?php echo $this->generateCartIframe(); ?>

    gle("OnCheckoutStepLoaded",function(data){
        switch(data.StepId){
            case data.Steps.SHIPPING:
            case data.Steps.REVIEW:
            case data.Steps.PAYMENT:
                break;
            case data.Steps.CONFIRMATION:
                jQuery.get("<?php echo Mage::helper('globale_browsing/checkout')->getClearCart(); ?>");
                <?php echo "//<![CDATA[ {$this->getJsOnSuccess()} //]]>\r\n"; ?>
                break;
        }
    });
</script>

<div id="checkoutContainer"></div>
