<?php /**@var $this Globale_Browsing_Block_ClientSDK  **/ ?>
<script type="text/javascript">
 	<?php echo $this->loadClientSdkJS();?>

    gle("OnShippingSwitcherClosed", function(e){
        if (e.isRedirect){
            if(getRedirectUrl(e.redirectURL)){
                var redirectURL = getRedirectUrl(e.redirectURL);
                if(!e.currency && jQuery){
                    e.currency = jQuery("#gle_selectedCurrency [data-currencyid=" + jQuery("#gle_selectedCountry :selected").attr("data-currency") + "]").val();
                } else if(!e.currency){
                    e.currency = '<?php echo $this->getStoreBaseCurrencyCode();?>';
                }
                GlobalE.ShippingSwitcher.Base.UpdateCustomerInfo(e.country, e.currency, true, redirectURL);
                return false;
            }
            else{
                GlobalE.ShippingSwitcher.Base.UpdateCustomerInfo(e.country, e.currency, true, window.location.href);
                return false;
            }
        }
        return true;
    });

    /**
     * Build Redirect Url according to selected store url
     * @param url - globale url according to switcher
     * @return string|false redirect url
     */
    function getRedirectUrl(url){
        //Array of all folder names
        var fullSuffixesList = <?php echo $this->loadRedirectSuffixList(); ?>;

        // Base Url of Magento admin https://example.com/
        var fullSiteBaseUrl = '<?php echo $this->getAdminBaseUrl(); ?>';

        // remove '/' from the end if exist -> https://example.com
        if (fullSiteBaseUrl.substr(-1) === '/') {
            fullSiteBaseUrl = fullSiteBaseUrl.slice(0, -1);
        }

        // sanitized Magento Base url example.com - strip http/https://
        var siteBaseUrl = fullSiteBaseUrl.replace(/(^\w+:|^)\/\//, '');

        var currentBaseUrl = window.location.href;
        //sanitised current url
        var currentUrl = currentBaseUrl.replace(/(^\w+:|^)\/\//, '');

        //sanitized checked country url
        var currentCountrySiteURL = url.replace(/(^\w+:|^)\/\//, '');


        var currentUrlSuffix = getUrlStoreSuffix(currentUrl, siteBaseUrl, fullSuffixesList);
        var currentCountrySiteSuffix = getUrlStoreSuffix(currentCountrySiteURL, siteBaseUrl, fullSuffixesList);

        if((currentCountrySiteURL) && currentCountrySiteSuffix !== null && currentUrlSuffix !== currentCountrySiteSuffix  ) {
            var RedirectUrl = '';
            <?php if(!$this->loadKeepOriginalUri()): ?>

            //redirect to homepage https://example.com/us or https://example.com/
            RedirectUrl = fullSiteBaseUrl + '/'+ currentCountrySiteSuffix ;

            <?php else:?>

            if (currentUrlSuffix !== '' && currentCountrySiteSuffix !== '') {
                // example.com/us/ties.html --> example.com/eu/ties.html
                RedirectUrl = currentBaseUrl.replace(siteBaseUrl + '/' + currentUrlSuffix, siteBaseUrl + '/' + currentCountrySiteSuffix);

            } else if (currentUrlSuffix !== '' && currentCountrySiteSuffix === '') {
                //example.com/us/ties.html --> example.com/ties.html
                RedirectUrl = currentBaseUrl.replace(siteBaseUrl+ '/' +currentUrlSuffix, siteBaseUrl);

            } else if (currentUrlSuffix === '' && currentCountrySiteSuffix !== '') {
                //example.com/ties.html --> example.com/eu/ties.html
                RedirectUrl = currentBaseUrl.replace(siteBaseUrl , siteBaseUrl + '/' + currentCountrySiteSuffix);

            }
            <?php endif; ?>
            return RedirectUrl;
        }
        return false;
    }

    /**
     * Find UrlStoreSuffix of url according to fullSuffixesList
     * @param url
     * @param siteBaseUrl
     * @param fullSuffixesList
     * @returns {string}
     */
    function getUrlStoreSuffix(url, siteBaseUrl, fullSuffixesList){

        var urlString = url.replace(siteBaseUrl,'');

        if (urlString.charAt(0) === '/') {
            urlString = urlString.slice(1);
        }

        var urlParts = urlString.split('/');
        var suffixOrder = 0;
        var urlStoreSuffix = '';

        if(urlParts[suffixOrder] === undefined) {
            urlStoreSuffix = '';
        }else if(fullSuffixesList.indexOf(urlParts[suffixOrder]) !== -1 ){
            urlStoreSuffix = urlParts[urlParts.indexOf(urlParts[suffixOrder])];
        }else if(fullSuffixesList.indexOf('') !== -1){
            urlStoreSuffix = '';
        }else{
            urlStoreSuffix = null;
        }
        return urlStoreSuffix;
    }

</script>