<?php
/**
 * Copyright (c) 2009-2015 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     vaimo_theme_carbon
 * @copyright   Copyright (c) 2009-2015 Vaimo AB
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Reset a Password'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
    <ul class="form-list">
        <li class="fields">
            <div class="field">
                <label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>
                <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
            </div>
            <div class="field">
                <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
                <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
            </div>
        </li>
    </ul>
    <div class="row">
        <div class="buttons-set col-xs-12 col-sm-12 col-md-12">
            <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
            <button type="submit" title="<?php echo $this->__('Reset a Password'); ?>" class="button"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
        </div>
    </div>
</form>
<script type="text/javascript">
    /*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
    /*]]>*/
</script>
