<?php
$isMobile= Mage::helper('abandonedcart/mobileDetect')->isMobile();

if (($isMobile && Mage::getStoreConfigFlag('abandonedcart/basic/enable')
        && Mage::getStoreConfigFlag('abandonedcart/frontend/lightbox_mobile')
        && (!$this->getQuote()->getId() || !$this->getEmailQuote()))
        || (!$isMobile && Mage::getStoreConfigFlag('abandonedcart/basic/enable') && Mage::getStoreConfigFlag('abandonedcart/frontend/lightbox_desktop') && (!$this->getQuote()->getId() || !$this->getEmailQuote()))) {
    //any lightbox will be open
    ?>
    <div class="bw_block_page" style="display:none;">
        <div class="bw_box">
            <input type="text" name="bw_cookie_expire_time" id="bw_cookie_expire_time" style="display: none;" value="<?php echo (int)Mage::getStoreConfig('web/cookie/cookie_lifetime'); ?>" />
            <a href="javascript:void(0);" title="<?php echo $this->__('Close')?>" onclick="closeLightbox(<?php echo (int)Mage::getStoreConfig('web/cookie/cookie_lifetime') ?>);abCartTrackEvent('Add2CartPrompt','No Thanks');" class="bw_box_close"></a>
            <form action="<?php echo $this->getAction(); ?>" method="post" id="bw-validate-detail" onsubmit="javascript:bwSubmitEmailForm();return false;">
                <div class="form-bw clearfix">
                    <div class="form-bw-header">
                        <div class="form-bw-header-logo"></div>
                        <div class="form-bw-header-right"></div>
                    </div>
                    <div class="form-bw-separator"></div>
                    <div class="form-bw-center"></div>
                    <div class="form-bw-legend"></div>
                    <div class="bw-input-box input-box">
                        <table class="desktop_input" style="display:none;">
                            <tr>
                                <td class="bwemail-td">
                                    <input type="text" name="email" id="bwemail_desktop" placeholder="<?php echo $this->__('example@email.com') ?>" title="<?php echo $this->__('Enter email address') ?>" class="input-text required-entry validate-email bw_box_input" />
                                </td>
                                <td>
                                    <button type="button" title="<?php echo $this->__('Save my cart')?>" class="bw_button" onclick="bwSubmitEmailForm();">
                                        <span><span><?php echo $this->__('SAVE MY CART')?></span></span>
                                    </button>
                                </td>
                            </tr>
                        </table>
                        <table class="mobile_input" style="display:none;">
                            <tr>
                                <td class="bwemail-td">
                                    <input type="text" name="email" id="bwemail_mobile" placeholder="<?php echo $this->__('example@email.com') ?>" title="<?php echo $this->__('Enter email address') ?>" class="input-text required-entry validate-email bw_box_input" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <button type="button" title="<?php echo $this->__('Save my cart')?>" class="bw_button" onclick="bwSubmitEmailForm();">
                                        <span><span><?php echo $this->__('SAVE MY CART')?></span></span>
                                    </button>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div id="pd_results"></div>
                    <div class="form-bw-bottom" title="<?php echo $this->__('No Thanks')?>" onclick="closeLightbox(<?php echo (int)Mage::getStoreConfig('web/cookie/cookie_lifetime') ?>);abCartTrackEvent('Add2CartPrompt','No Thanks');">
                        <span class="no-thanks"></span>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">
        //<![CDATA[
        function isValidEmailAddress(emailAddress) {
            var pattern = /^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/i;
            return pattern.test(emailAddress);
        };

        function bwSubmitEmailForm(){
            var email='';
            if ( jQuery('.desktop_input').is(':visible') ) {
                email= jQuery('#bwemail_desktop').val();
            } else {
                email= jQuery('#bwemail_mobile').val();
            }

            if(!isValidEmailAddress(email)) {
                jQuery('#pd_results').css("color","#ff0000");
                jQuery('#pd_results').html('Please use a valid email address');
                jQuery('#pd_results').show();
                return;
            }

            jQuery('#pd_results').hide();
            jQuery.ajax({
                url: jQuery('#bw-validate-detail').attr('action'),
                type: "POST",
                data: {'isAjax':1,'email':email, 'type':'add2cart'},
                success: function(data) {
                    abCartTrackEvent('Add2CartPrompt','Email Entered');
                    jQuery('#pd_results').css("color","#006600");
                    jQuery('#pd_results').css("background-color","yellow");
                    jQuery('#pd_results').css("text-align","center");
                    jQuery('#pd_results').html("<?php echo $this->__("Thanks - we'll email you a link to this cart"); ?>");
                    jQuery('#pd_results').show();

                    setTimeout(function(){
                        jQuery('.bw_block_page').hide();
                    },4000);
                },
                error:function(data) {
                    jQuery('#pd_results').css("color","#ff0000");
                    jQuery('#pd_results').html('Please try again later');
                    jQuery('#pd_results').show();
                    jQuery('#bwemail_desktop').val('');
                    jQuery('#bwemail_mobile').val('');
                    jQuery('.bw_box').hide();
                    jQuery('.bw_block_page').hide();
                }
            });
            return false;
        }

        <?php if(!$this->getEmailQuote()): ?>
            setTimeout(openLightBox(<?php echo (int)Mage::getStoreConfig('web/cookie/cookie_lifetime'); ?>), 500);
        <?php endif; ?>
        //]]>
    </script>
<?php } ?>
