<?php
/** @var $this Cryozonic_StripeExpress_Block_Button */

// Workaround to ensure that only the top Apple Pay button is rendered:

if ($this->hasData('applepay_rendered') && $this->getData('applepay_rendered')) {
    return;
}
$this->setData('applepay_rendered', true);
?>

<?php if ($this->isEnabled('cart_button')):
    $params = $this->getButtonConfig();
    $params['buttonId'] = uuid('payment-request-', 26);
    ?>
    <div id="<?php echo $params['buttonId'] ?>" class="stripeexpress-payment-button">&nbsp;</div>
    <script type="text/javascript">
        //<![CDATA[
        var MAGENTO_BASE_URL = '<?php echo $this->jsQuoteEscape(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true)); ?>';
        Event.observe(document, 'dom:loaded', function () {
            stripeExpress.initStripeExpress('<?php echo $this->getPublishableKey(); ?>', <?php echo json_encode($this->getApplePayParams()); ?>, <?php echo json_encode($params); ?>, function (paymentRequest, params,
                                                                                        prButton) {
                stripeExpress.initCartWidget(paymentRequest, params, prButton);
            });
        });
        //]]>
    </script>
    <li class="bml-checkout-type stripeexpress-or-line">
        <p class="stripexpress-logo paypal-logo" style="display: none;">
            <span class="paypal-or"><?php echo $this->__('-OR-'); ?></span>
        </p>
    </li>
<?php endif; ?>

