<?php
/**
 * @author    Mediotype Development <diveinto@mediotype.com>
 * @copyright 2019 Mediotype. All rights reserved.
 */
/** @var $this Mage_Catalog_Block_Product_View */
?>
<?php
$_helper = $this->helper('socialreferrals');
?>
<?php if (!empty($_helper->getSiteId())) : ?>
    <?php $_product = $this->getProduct() ?>
    <?php if ($_product && $_product->getIsSharable()): ?>
        <?php $_imageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $_product->getImage(); ?>
        <div id="talkable-product-sharing"></div>
        <script>
            window._tkbl_data = {
                product: {
                    sku: '<?php echo $_product->getSku() ?>',
                    title: '<?php echo $this->escapeHtml($_product->getName()) ?>',
                    image_url: '<a href="<?php echo $_imageUrl  ?>" rel="noopener" target="_blank"><?php echo $_imageUrl ?></a>'
                }
            };
        </script>
    <?php endif ?>
<?php endif ?>
