<?php echo $this->getChildHtml('form_fields_before')?>
    
<form action="<?php echo $this->getPostActionUrl() ?>" id="signup-validate" method="post" class="signup-widget">
    <input type="hidden" name="customer_group_id" value="<?php echo $this->getCustomerGroupId();?>" />
    <input type="hidden" name="success_url" value="">
    <input type="hidden" name="error_url" value="<?php echo Mage::helper('core/url')->getCurrentUrl();?>">
    <input name="form_key" type="hidden"
           value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
    
    <ul><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?></ul>
    
    <label for="email" class="required"><?php echo $this->__('Email Address');?> <span class="required">*</span></label>
    <input type="text" id="email" name="email" class="input-text required-entry validate-email" />
    
    <label for="password" class="required"><?php echo $this->__('Password');?> <span class="required">*</span></label>
    <input type="password" id="password" name="password" class="input-text required-entry validate-password" />
    
    <label for="confirmation" class="required"><?php echo $this->__('Confirm Password');?> <span class="required">*</span></label>
    <input type="password" id="confirmation" name="confirmation" class="input-text required-entry validate-cpassword" />
    
    <?php if ($this->isNewsletterEnabled()): ?>
        <input type="hidden" name="is_subscribed" value="1" />
    <?php endif ?>
    
    <div class="std signup-widget__cms"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('create_account_information_block')->toHtml() ?></div>
    
    <div>
        <input type="submit" class="button" value="<?php echo $this->__('submit');?>" />
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('signup-validate', false);
//]]>
</script>