<?php
/** @var Vaimo_Hylete_Block_Widgets_Signup_Extended $this */
echo $this->getChildHtml('form_fields_before');
?>

<form action="<?php echo $this->getPostActionUrl() ?>" id="signup-validate" method="post"
      class="signup-widget">
    <input type="hidden" name="customer_group_id"
           value="<?php echo $this->getCustomerGroupId(); ?>"/>
    <input type="hidden" name="success_url" value="">
    <input type="hidden" name="error_url"
           value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>">
    <input name="form_key" type="hidden"
           value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
    <div class="row">
        <div class="col-md-6">
            <h2 class="legend"><?php echo $this->__('Your Name') ?></h2>
            <ul>
                <?php echo $this->getLayout()
                    ->createBlock('customer/widget_name')
                    ->setObject($this->getFormData())
                    ->setForceUseCustomerAttributes(true)
                    ->toHtml() ?>

                <li><?php echo $this->getLayout()
                        ->createBlock('customer/widget_gender')
                        ->setObject($this->getFormData())
                        ->setForceUseCustomerAttributes(true)
                        ->toHtml() ?>
                </li>
            </ul>
        </div>
        <div class="col-md-6">
            <h2 class="legend section"><?php echo $this->__('Account Info') ?></h2>
            <label for="email_address" class="required"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label>
            <input type="email" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="span4 input-text validate-email required-entry" />

            <label for="password" class="required"><?php echo $this->__('Password'); ?> <span
                    class="required">*</span></label>
            <input type="password" id="password" name="password"
                   class="input-text required-entry validate-password"/>

            <label for="confirmation" class="required"><?php echo $this->__('Confirm Password'); ?> <span
                    class="required">*</span></label>
            <input type="password" id="confirmation" name="confirmation"
                   class="input-text required-entry validate-cpassword"/>
            <?php if ($this->isNewsletterEnabled()): ?>
                <input type="hidden" name="is_subscribed" value="1"/>
            <?php endif ?>
            <?php echo $this->getChildHtml('rewards_referral'); ?>

            <div class="second-section">
                <div class="first-heard">
                    <?php echo $this->getAttributeLabel('first_heard', true); ?>
                    <?php echo $this->getInputHtml('first_heard', true); ?>
                    <div class="select-other">
                        <?php echo $this->getAttributeLabel('first_heard_other'); ?>
                        <?php echo $this->getInputHtml('first_heard_other'); ?>
                    </div>
                </div>
                <div class="select-event show-on-condition">
                    <?php echo $this->getAttributeLabel('first_heard_event'); ?>
                    <?php echo $this->getInputHtml('first_heard_event'); ?>
                    <div class="select-other">
                        <?php echo $this->getAttributeLabel('first_heard_event_o'); ?>
                        <?php echo $this->getInputHtml('first_heard_event_o'); ?>
                    </div>
                </div>
                <div class="select-magazine show-on-condition">
                    <?php echo $this->getAttributeLabel('first_heard_mag'); ?>
                    <?php echo $this->getInputHtml('first_heard_mag'); ?>
                    <div class="select-other">
                        <?php echo $this->getAttributeLabel('first_heard_mag_o'); ?>
                        <?php echo $this->getInputHtml('first_heard_mag_o'); ?>
                    </div>
                </div>
                <div class="select-person show-on-condition">
                    <?php echo $this->getAttributeLabel('first_heard_pers'); ?>
                    <?php echo $this->getInputHtml('first_heard_pers'); ?>
                    <div class="select-other">
                        <?php echo $this->getAttributeLabel('first_heard_pers_o'); ?>
                        <?php echo $this->getInputHtml('first_heard_pers_o'); ?>
                    </div>
                </div>
                <div class="select-organization show-on-condition">
                    <?php echo $this->getAttributeLabel('first_heard_org'); ?>
                    <?php echo $this->getInputHtml('first_heard_org'); ?>
                    <div class="select-other">
                        <?php echo $this->getAttributeLabel('first_heard_org_o'); ?>
                        <?php echo $this->getInputHtml('first_heard_org_o'); ?>
                    </div>
                </div>
                <div class="select-online-ad show-on-condition">
                    <?php echo $this->getAttributeLabel('first_heard_ad'); ?>
                    <?php echo $this->getInputHtml('first_heard_ad'); ?>
                    <div class="select-other">
                        <?php echo $this->getAttributeLabel('first_heard_ad_o'); ?>
                        <?php echo $this->getInputHtml('first_heard_ad_o'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-md-push-6">
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button>
        <div class="std"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('create_account_information_block')->toHtml() ?></div>
    </div>
</form>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('signup-validate', false);
    //]]>
</script>
