<?php
/**
 * Copyright (c) 2009-2016 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Hylete
 * @copyright   Copyright (c) 2009-2016 Vaimo AB
 */
?>

<div class="block block-account">
    <div class="block-title">
        <h1><?php echo $this->__('my account'); ?></h1>
    </div>
    <div class="block-content">
        <ul>
            <?php $_links = $this->getLinks(); ?>

            <?php $_isLogOutExist = isset($_links['Logout']); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($_link->getName() != 'Logout'): ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last && !$_isLogOutExist ? ' last' : '') ?>"><span><?php echo $_link->getLabel() ?></span></li>
                <?php else: ?>
                    <li<?php echo ($_last && !$_isLogOutExist ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($_isLogOutExist): ?>
                <li class="last"><a href="<?php echo $_links['Logout']->getUrl() ?>"><?php echo $_links['Logout']->getLabel() ?></a></li>
            <?php endif; ?>
        </ul>
    </div>
</div>
