<?php
/**
 * Sweet Tooth
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Sweet Tooth SWEET TOOTH POINTS AND REWARDS
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth License is available at this URL:
 *     https://www.sweettoothrewards.com/terms-of-service
 * The Open Software License is available at this URL:
 *      http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * By adding to, editing, or in any way modifying this code, Sweet Tooth is
 * not held liable for any inconsistencies or abnormalities in the
 * behaviour of this code.
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by Sweet Tooth, outlined in the
 * provided Sweet Tooth License.
 * Upon discovery of modified code in the process of support, the Licensee
 * is still held accountable for any and all billable time Sweet Tooth spent
 * during the support process.
 * Sweet Tooth does not guarantee compatibility with any other framework extension.
 * Sweet Tooth is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to
 * support@sweettoothrewards.com or call 1.855.699.9322, so we can send you a copy
 * immediately.
 *
 * @category   [TBT]
 * @package    [TBT_Rewards]
 * @copyright  Copyright (c) 2014 Sweet Tooth Inc. (http://www.sweettoothrewards.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/**
 * Admin Order Create Product Search Item Rewards Info
 *
 * @category   TBT
 * @package    TBT_Rewards
 * @author     Sweet Tooth Inc. <support@sweettoothrewards.com>
 */
?>
<?php 
    $pointsHtmlContainer = '<span class="rewards-product-info-discount-points bold"></span>';
    $amountHtmlContainer = '<span class="rewards-product-info-discount-price bold"></span>';
?>
<?php if ($this->isRedemptionAllowedByProductType()) : ?>
    <?php if ($this->hasRulesProduct()) : ?>
    <span class="grid-product-search-rewards-configure f-right" list_type="product_to_rewards" product_id="<?php echo $this->getProduct()->getId(); ?>" can-configure="<?php echo ($this->canConfigure()) ? 1 : 0; ?>"><?php echo Mage::helper('rewards')->__('Rewards Spending'); ?></span>
    <?php endif;?>

    <?php echo $this->getProductRendererHtml(); ?>

    <?php if ($this->hasPointsOnlyRules()) : ?>
    <div class="rewards-product-info-container" points-only="true" style="display:none;" product_id="<?php echo $this->getProduct()->getId(); ?>">

            <?php echo Mage::helper('rewards')->__(
                'Customer will spend %s points on this points-only product',
                '<span class="rewards-product-info-discount-points bold">'.$this->getPointsOnlyValue().'</span>'
            );?>
    </div>
    <?php else : ?>
    <div class="rewards-product-info-container" style="display:none;" product_id="<?php echo $this->getProduct()->getId(); ?>">
            <?php echo Mage::helper('rewards')->__('Customer will spend %s points, for a %s discount', $pointsHtmlContainer, $amountHtmlContainer);?>
            <img class="rewards-product-info-remove" src="<?php echo Mage::getDesign()->getSkinUrl('rewards/images/remove.gif');?>"/>
    </div>
    <?php endif; ?>

    <?php if ($this->hasPointsOnlyRules()) : ?>
        <script type="text/javascript">
            sweettooth.addSweettoothGlobalVar(
                'rewardsMapPointsOnly',
                {<?php echo $this->getProduct()->getId(); ?> : '<?php echo $this->getPointsOnlyString();?>'}
            );
        </script>
    <?php endif; ?>
<?php else : ?>
    <?php echo $this->getProductRendererHtml(); ?>
<?php endif; ?>
